import {readNativeDictionary} from './native-resource-dictionary.mjs';
export function readNativeTextureResource(bytes){
 const d=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength),magic=a=>String.fromCharCode(...bytes.subarray(a,a+4)),need=(a,n)=>{if(a<0||a+n>bytes.length)throw new Error('Native texture resource span outside file');};need(0,16);if(!['BTX0','BMD0'].includes(magic(0))||d.getUint16(4,true)!==0xfeff)throw new Error('Little-endian BTX0/BMD0 required');
 const sections=d.getUint16(14,true);need(16,sections*4);const blocks=[];for(let i=0;i<sections;i++){const offset=d.getUint32(16+4*i,true);need(offset,8);const size=d.getUint32(offset+4,true);need(offset,size);blocks.push({offset,size,magic:magic(offset)});}const tex=blocks.find(b=>b.magic==='TEX0');if(!tex)return {blocks,textureSection:null,textures:[],palettes:[]};
 const base=tex.offset,end=base+tex.size;need(base,60);const header={base,end,regularDataUnits:d.getUint16(base+12,true),textureDictOffset:d.getUint16(base+14,true),regularDataOffset:d.getUint32(base+20,true),compressedDataUnits:d.getUint16(base+28,true),compressedDictOffset:d.getUint16(base+30,true),compressedDataOffset:d.getUint32(base+36,true),compressedIndexOffset:d.getUint32(base+40,true),paletteDataUnits:d.getUint16(base+48,true),paletteDictOffset:d.getUint16(base+52,true),paletteDataOffset:d.getUint32(base+56,true)},textureDict=readNativeDictionary(bytes,base+header.textureDictOffset,end),paletteDict=readNativeDictionary(bytes,base+header.paletteDictOffset,end),span=(a,n)=>{if(a<base||a+n>end)throw new Error('TEX0 payload outside section');return {offset:a,bytes:n};};
 if(textureDict.stride!==8||paletteDict.stride!==4)throw new Error('Unsupported native TEX0 entry widths');span(base+header.regularDataOffset,header.regularDataUnits*8);span(base+header.compressedDataOffset,header.compressedDataUnits*8);span(base+header.compressedIndexOffset,header.compressedDataUnits*4);span(base+header.paletteDataOffset,header.paletteDataUnits*8);
 const textures=textureDict.rows.map(r=>{const parameter=d.getUint32(r.entryOffset,true),extraParameter=d.getUint32(r.entryOffset+4,true),format=parameter>>>26&7,width=8<<((parameter>>>20)&7),height=8<<((parameter>>>23)&7),offset=(parameter&65535)*8,bitsPerPixel=[0,8,2,4,8,2,8,16][format],dataBytes=width*height*bitsPerPixel/8,data=span(base+(format===5?header.compressedDataOffset:header.regularDataOffset)+offset,dataBytes),compressedIndex=format===5?span(base+header.compressedIndexOffset+offset/2,width*height/8):null;return {...r,parameter,extraParameter,format,width,height,keyColor0:Boolean(parameter&0x20000000),repeatS:Boolean(parameter&0x10000),repeatT:Boolean(parameter&0x20000),flipS:Boolean(parameter&0x40000),flipT:Boolean(parameter&0x80000),textureTransformMode:parameter>>>30,sourcePayloadOffset:offset,data,compressedIndex};});
 const palettes=paletteDict.rows.map(r=>({...r,paletteOffsetUnits:d.getUint16(r.entryOffset,true),paletteDataOffset:base+header.paletteDataOffset+d.getUint16(r.entryOffset,true)*8,rawFlags:d.getUint16(r.entryOffset+2,true)}));return {blocks,textureSection:header,textureDict,paletteDict,textures,palettes};
}
