import {parseCSV} from './map-core.mjs';
import {markerCoordinateBinding} from './map-marker-coordinate.mjs';
const $=id=>document.getElementById(id),ui=Object.fromEntries(['rom','status','rom-name','release','mode','search','has-image','count','list','title','identity','descriptor','zoom','background','map','viewport','empty','image-info','facts','summary','raw','errors','export-all','export-csv','export-one','export-png','export-asset','enc-table','enc-results'].map(id=>[id,$(id)]));
let metadata=null,worker=null,selection=null,selectedAsset=null,requestId=0,image=null,loadSerial=0,rows=[],nameCSV='',encounters=null;
const state={mode:'maps'};
const status=(text,error=false)=>{ui.status.textContent=text;ui.status.classList.toggle('error',error);};
const pretty=x=>JSON.stringify(x,null,2);
function download(name,content,type='application/json'){const blob=content instanceof Blob?content:new Blob([content],{type});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
const safeName=x=>(x||'map').replace(/[\\/:*?"<>|]/g,'_');
function clearPreview(message){image=null;window.dispatchEvent(new CustomEvent('dq9-map-image',{detail:null}));ui.map.hidden=true;ui.empty.hidden=false;ui.empty.textContent=message;ui['export-png'].disabled=true;ui['image-info'].textContent='マップ素材の合成表示。カメラ・現在位置・アイコンはまだ重ねません。';}
function release(){loadSerial++;worker?.terminate();worker=null;metadata=null;selection=null;selectedAsset=null;requestId++;ui.release.disabled=true;ui['rom-name'].textContent='ファイルをドロップ';for(const id of ['export-all','export-csv','export-one','export-asset'])ui[id].disabled=true;ui.descriptor.replaceChildren(new Option('未選択',''));ui.descriptor.disabled=true;ui.facts.replaceChildren();ui.raw.textContent='';ui.summary.textContent='NDS未読込';ui.errors.textContent='なし';ui.title.textContent='NDS未選択';ui.identity.textContent='既存の日本語マップ名を表示できます。';clearPreview('NDSをここへドロップ');window.dispatchEvent(new CustomEvent('dq9-rom-release'));renderList();}
async function loadROM(file){if(!file)return;if(!/\.nds$/i.test(file.name)){status('NDSファイルを選択してください。',true);return;}release();const serial=loadSerial;status('NDSを読込中');ui['rom-name'].textContent=file.name;ui.release.disabled=false;
 try{await namesReady;const buffer=await file.arrayBuffer();if(serial!==loadSerial)return;
  worker=new Worker(new URL('./worker.mjs',import.meta.url),{type:'module'});worker.onerror=e=>status('Worker: '+e.message,true);
  worker.onmessage=({data:m})=>{
   if(serial!==loadSerial)return;
   if(m.type==='progress')status(m.message);
   else if(m.type==='loaded'){metadata=m.metadata;window.dispatchEvent(new CustomEvent('dq9-rom-metadata',{detail:metadata}));ui['export-all'].disabled=false;ui['export-csv'].disabled=false;const s=metadata.summary;ui.summary.textContent=`マップ ${s.records}件 / 配置 ${s.descriptors}件 / 画像 ${s.images}件 / 特殊パック ${s.packs}件（画像化 ${s.pacImages}件）。配置候補を持つマップ ${s.recordsWithMap}件。`;ui.errors.textContent=metadata.errors.length?pretty(metadata.errors):'なし';status(`採掘完了 · ${metadata.rom.gameCode} · Worker + WebAssembly`);renderList();const preferred=rows.find(r=>r.data.mapId===7402)||rows[0];if(preferred)select(preferred);}
   else if(m.type==='image'){if(m.requestId!==requestId)return;image=m.image;ui.map.width=image.width;ui.map.height=image.height;ui.map.getContext('2d').putImageData(new ImageData(image.rgba,image.width,image.height),0,0);ui.map.hidden=false;ui.empty.hidden=true;ui['export-png'].disabled=false;zoom();ui['image-info'].textContent=`${image.width} × ${image.height} px · ${image.parts?image.parts.length+' layer合成':image.format==='PAC'?'特殊マップ素材（生成階層の配置・探索状況とは別）':'タイル画像'}${image.originPixel?' · 原点 '+image.originPixel.join(', '):''} · WASM`;status('表示完了');window.dispatchEvent(new CustomEvent('dq9-map-image',{detail:{...image,markerCoordinateBinding:markerCoordinateBinding(image.descriptor,selection?.kind==='map'?selection.data.mapId:null),worldToMapScale:image.descriptor?.worldToMapScale??null,mapId:selection?.kind==='map'?selection.data.mapId:null,descriptor:ui.descriptor.value}}));}
   else if(m.type==='map-candidates')window.dispatchEvent(new CustomEvent('dq9-map-candidates-result',{detail:m}));
   else if(m.type==='map-candidates-error')window.dispatchEvent(new CustomEvent('dq9-map-candidates-result',{detail:m}));
   else if(m.type==='fonts')window.dispatchEvent(new CustomEvent('dq9-runtime-fonts',{detail:m.fonts}));
   else if(m.type==='font-error')window.dispatchEvent(new CustomEvent('dq9-font-error',{detail:m.message}));
   else if(m.type==='monster-assets')window.dispatchEvent(new CustomEvent('dq9-monster-assets',{detail:{requestId:m.requestId,assets:m.assets}}));
   else if(m.type==='monster-assets-error')window.dispatchEvent(new CustomEvent('dq9-monster-assets-error',{detail:{requestId:m.requestId,message:m.message}}));
   else if(m.type==='monster-preview')window.dispatchEvent(new CustomEvent('dq9-monster-preview',{detail:{requestId:m.requestId,preview:m.preview}}));
   else if(m.type==='monster-preview-error')window.dispatchEvent(new CustomEvent('dq9-monster-preview-error',{detail:{requestId:m.requestId,message:m.message}}));
   else if(m.type==='asset')download(m.name,m.bytes,'application/octet-stream');
   else if(m.type==='error'){if(m.requestId!==undefined&&m.requestId!==requestId)return;status(m.message,true);clearPreview(m.message);}
  };worker.postMessage({type:'load',buffer,csv:nameCSV},[buffer]);
 }catch(error){if(serial===loadSerial)status(error.message,true);}
}
function getRows(){const mode=ui.mode.value;
 if(!metadata){if(mode!=='maps')return [];return parseCSV(nameCSV).map(r=>({key:'catalog:'+r.mapId,label:r.nameJa,sub:`${r.mapIdHex} · ${r.mapId} · 既存CSV`,data:r,kind:'catalog'}));}
 if(mode==='maps')return metadata.records.map(r=>({key:r.key,label:r.name||r.fieldCode||r.mapIdHex,sub:`${r.mapIdHex} · ${r.mapId} · ${r.fieldCode??'—'}${r.candidates.length?'':' · 配置未結合'}`,kind:'map',data:r}));
 if(mode==='descriptors')return metadata.descriptors.map(d=>({key:d.key,label:d.path,sub:`${d.layers.length} layer · ${d.placements.length}配置 · ${d.mapBindings.length}結合`,kind:'descriptor',data:d}));
 return metadata.assets.filter(a=>mode==='images'?a.info:mode==='packs'?a.path.endsWith('.pac'):true).map(a=>({key:a.key,label:a.path,sub:`${a.info?a.info.width+'×'+a.info.height+' px · ':''}${a.size.toLocaleString()} B · ${a.archive.split('/').pop()}`,kind:'asset',data:a}));
}
function renderList(){const q=ui.search.value.trim().normalize('NFKC').toLowerCase();rows=getRows().filter(r=>(!q||(r.label+' '+r.sub).normalize('NFKC').toLowerCase().includes(q))&&(!ui['has-image'].checked||r.kind==='descriptor'||r.data.info||r.data.candidates?.length));ui.count.textContent=`${rows.length.toLocaleString()}件`;const fragment=document.createDocumentFragment();for(const r of rows){const b=document.createElement('button');b.className='row';b.type='button';b.setAttribute('role','option');b.setAttribute('aria-selected',String(selection?.key===r.key));b.dataset.key=r.key;const title=document.createElement('strong'),sub=document.createElement('small');title.textContent=r.label;sub.textContent=r.sub;b.append(title,sub);b.onclick=()=>select(r);fragment.append(b);}ui.list.replaceChildren(fragment);}
function facts(pairs){ui.facts.replaceChildren();for(const [label,value] of pairs){const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=label;dd.textContent=value==null?'—':String(value);ui.facts.append(dt,dd);}}
function select(row){selection=row;selectedAsset=null;requestId++;clearPreview('読込中');ui.title.textContent=row.label;ui.identity.textContent=row.sub;ui.raw.textContent=pretty(row.data);ui['export-one'].disabled=false;ui['export-asset'].disabled=true;ui.descriptor.replaceChildren();ui.descriptor.disabled=true;
 if(row.kind==='map'){const r=row.data;window.dispatchEvent(new CustomEvent('dq9-map-selection',{detail:{mapId:r.mapId,name:r.name,fieldCode:r.fieldCode,source:'map-browser-selection'}}));facts([['map ID',r.mapIdHex+' / '+r.mapId],['名称',r.name],['内部ラベル',r.internalLabel],['field code',r.fieldCode],['secondary ID',r.secondaryId],['model resource',r.modelResource],['出典',r.source.path+' @ '+r.source.callOffset],['field graph',r.fieldGraph?.requestedPath+' / '+r.fieldGraph?.status],['node areas',r.fieldGraph?.areaMasks.join(', ')],['encounter context',r.encounterContexts?.length?'ノード位置と時間で候補を選択':'静的参照なし']]);for(const c of r.candidates)ui.descriptor.add(new Option(c.path+' · '+c.relation,c.path));ui.descriptor.disabled=!r.candidates.length;if(r.candidates.length)renderDescriptor();else clearPreview('通常配置との結合は未確定です。配置・特殊パック一覧から素材を参照できます。');}
 else if(row.kind==='descriptor'){const d=row.data;ui.descriptor.add(new Option(d.path,d.path));ui.descriptor.disabled=false;facts([['出典',d.archive+' :: '+d.path],['原点（tile）',d.originTile.join(', ')],['縮尺',d.worldToMapScale],['背景',d.background],['map結合',d.mapBindings.map(x=>x.mapId).join(', ')]]);renderDescriptor();}
 else if(row.kind==='asset'){const a=row.data;selectedAsset=a.key;ui['export-asset'].disabled=false;facts([['出典',a.archive],['member',a.path],['サイズ',a.size+' B'],['寸法',a.info?a.info.width+' × '+a.info.height:'—'],['色深度',a.info?.bpp? a.info.bpp+' bpp':'—']]);if(a.info)worker.postMessage({type:'render',key:a.key,requestId:++requestId});else clearPreview(a.path.endsWith('.pac')?'特殊マップのパックです。内包タイルと配置の対応は解析中です。':'この素材は画像プレビュー対象ではありません。元データを保存できます。');}
 else {facts(Object.entries(row.data));clearPreview('このマップの素材を表示するにはNDSを選択してください。');}
 for(const b of ui.list.children)b.setAttribute('aria-selected',String(b.dataset.key===row.key));
}
function renderDescriptor(){if(!ui.descriptor.value||!worker)return;const d=metadata.descriptors.find(d=>d.path===ui.descriptor.value);selectedAsset=d?.key??null;ui['export-asset'].disabled=!selectedAsset;clearPreview('WASMで合成中');worker.postMessage({type:'render',descriptor:ui.descriptor.value,requestId:++requestId});if(selection?.kind==='map')ui.raw.textContent=pretty({map:selection.data,selectedDescriptor:d});}
function zoom(){if(!image)return;let scale=Number(ui.zoom.value);if(ui.zoom.value==='fit')scale=Math.max(.1,Math.min((ui.viewport.clientWidth-36)/image.width,(ui.viewport.clientHeight-36)/image.height));ui.map.style.width=Math.round(image.width*scale)+'px';ui.map.style.height=Math.round(image.height*scale)+'px';}
window.addEventListener('dq9-map-candidates-request',e=>{const m=e.detail;if(worker)worker.postMessage({...m,type:'map-candidates'},[m.frame.rgba.buffer]);else window.dispatchEvent(new CustomEvent('dq9-map-candidates-result',{detail:{type:'map-candidates-error',requestId:m.requestId,stamp:m.stamp,message:'NDSを先に投入してください'}}));});
window.addEventListener('dq9-font-request',()=>{if(worker)worker.postMessage({type:'fonts'});else window.dispatchEvent(new CustomEvent('dq9-font-error',{detail:'NDSを先に投入してください'}));});
window.addEventListener('dq9-monster-assets-request',e=>{if(worker)worker.postMessage({type:'monster-assets',requestId:e.detail?.requestId,models:e.detail?.models});else window.dispatchEvent(new CustomEvent('dq9-monster-assets-error',{detail:{requestId:e.detail?.requestId,message:'NDSを先に投入してください'}}));});
window.addEventListener('dq9-monster-preview-request',e=>{if(worker)worker.postMessage({type:'monster-preview',requestId:e.detail?.requestId,model:e.detail?.model});else window.dispatchEvent(new CustomEvent('dq9-monster-preview-error',{detail:{requestId:e.detail?.requestId,message:'NDSを先に投入してください'}}));});
window.addEventListener('dq9-view-map-request',e=>{const r=metadata?.records.find(r=>r.mapId===e.detail.mapId);if(r){ui.mode.value='maps';ui.search.value='';ui['has-image'].checked=false;renderList();const row=rows.find(x=>x.data===r);if(row){select(row);if(e.detail.descriptor&&r.candidates.some(c=>c.path===e.detail.descriptor)&&ui.descriptor.value!==e.detail.descriptor){ui.descriptor.value=e.detail.descriptor;renderDescriptor();}}}});
ui.rom.onchange=()=>loadROM(ui.rom.files[0]);ui.release.onclick=()=>{release();ui.rom.value='';status('NDSを解放しました。');};ui.mode.onchange=renderList;ui.search.oninput=renderList;ui['has-image'].onchange=renderList;ui.descriptor.onchange=renderDescriptor;ui.zoom.onchange=zoom;ui.background.onchange=()=>ui.viewport.className='viewport '+ui.background.value;new ResizeObserver(()=>{if(ui.zoom.value==='fit')zoom();}).observe(ui.viewport);
ui['export-all'].onclick=()=>download('dq9-map-metadata.json',pretty(metadata));
ui['export-one'].onclick=()=>{if(selection)download(safeName(selection.label)+'.json',ui.raw.textContent);};
ui['export-csv'].onclick=()=>{const columns=['mapIdHex','mapId','name','secondaryId','fieldCode','internalLabel','modelResource','areaStatus'];const quote=v=>'"'+String(v??'').replaceAll('"','""')+'"';download('dq9-map-catalog.csv','\ufeff'+[columns.map(quote).join(','),...metadata.records.map(r=>columns.map(c=>quote(r[c])).join(','))].join('\r\n'),'text/csv;charset=utf-8');};
ui['export-png'].onclick=()=>ui.map.toBlob(blob=>{if(blob)download(safeName(ui.descriptor.value||selection?.label)+'.png',blob);},'image/png');ui['export-asset'].onclick=()=>{if(selectedAsset)worker?.postMessage({type:'asset',key:selectedAsset});};
for(const ev of ['dragenter','dragover'])document.addEventListener(ev,e=>{e.preventDefault();document.body.classList.add('dragging');});document.addEventListener('dragleave',e=>{if(!e.relatedTarget)document.body.classList.remove('dragging');});document.addEventListener('drop',e=>{e.preventDefault();document.body.classList.remove('dragging');loadROM(e.dataTransfer.files[0]);});
const namesReady=fetch('./data/map-id-names.csv').then(r=>{if(!r.ok)throw Error('既存マップ名CSVがありません');return r.text();}).then(text=>{nameCSV=text;renderList();}).catch(e=>{status(e.message,true);throw e;});
fetch('./data/enc.json').then(r=>{if(!r.ok)throw Error('enc.jsonを取得できません');return r.json();}).then(data=>{encounters=data.main;for(const [key,t] of Object.entries(encounters))ui['enc-table'].add(new Option(`${t.id||key} · 最大乱数 ${t.maxRand}`,key));}).catch(e=>ui['enc-results'].textContent=e.message);
ui['enc-table'].onchange=()=>{ui['enc-results'].replaceChildren();const t=encounters?.[ui['enc-table'].value];if(!t)return;const table=document.createElement('table'),head=document.createElement('tr');for(const text of ['monster ID','モンスター','乱数範囲','trap']){const th=document.createElement('th');th.textContent=text;head.append(th);}table.append(head);for(const m of t.data||[]){const tr=document.createElement('tr');for(const value of [m.monsterId,m.monsterName,`${m.start} … ${m.end}`,m.trapMonster??'']){const td=document.createElement('td');td.textContent=String(value);tr.append(td);}table.append(tr);}ui['enc-results'].append(table);};
