import {storeSessionIdentification} from './at-session-identification.mjs';
import {attachNpcReplayPanel} from './npc-at-replay-panel.mjs';
import {metalCatalog} from './monster-catalog.mjs';
const $=id=>document.getElementById(id);
const panel=document.createElement('section');panel.className='at-panel';panel.innerHTML=`<div class="at-heading"><h2>AT追跡・メタル候補</h2><span id="at-state">未開始</span></div><div class="at-controls"><label>既知initial seed <input id="at-seed" placeholder="0x12345678" autocomplete="off" spellcheck="false"></label><button id="at-start">起動から追跡開始</button><button id="at-save" disabled>追跡を保存</button><button id="at-identify-session" disabled>記録した観測から候補を絞る</button><label class="file-button">追跡を復元<input id="at-restore" type="file" accept=".json"></label></div><div class="at-metrics"><div><small>証明済み下限</small><strong id="at-bound">—</strong></div><div><small>観測仮定つき下限</small><strong id="at-conditional">—</strong></div><div><small>未探索の先</small><strong>候補を保持</strong></div></div><div class="at-controls"><label>table ID <input id="at-table" type="number" min="0" value="30"></label><label>探索窓 <input id="at-window" type="number" min="1" max="1000000" value="50000"></label><label>対象 <select id="at-target"><option value="">読込中</option></select></label><label><input id="at-use-conditional" type="checkbox">観測仮定の分岐を使う</label><button id="at-search">次の対象候補</button></div><div id="at-context" class="muted">現在のmap/areaは未接続。table IDは自動確定しません。</div><div class="at-controls"><label>観測monster <select id="at-monster"></select></label><label><input id="at-natural" type="checkbox">自然生成と確認</label><button id="at-observe">新しい出現を記録</button></div><div id="at-message" role="status">見えているmonsterだけでは自然生成経路・正しいエリア表は証明できません。観測仮定と証明済み下限を分けて保持します。</div><div id="at-envelope" class="muted"></div><div class="at-controls"><label>未解決の消費区間 <select id="at-consumer"><option value="NPC-movement">NPC移動</option><option value="pots-barrels">つぼ・たる</option><option value="map-entry">マップ入場・初期化</option><option value="unclassified">その他・不明</option></select></label><button id="at-unknown">区間を記録</button></div><div id="at-forecast"></div><details><summary>起動連続trace / 実測replay</summary><label class="file-button">trace JSONを読む<input id="at-trace" type="file" accept=".json"></label><div id="at-replay"></div><section id="at-npc-replay"></section></details><details><summary>証拠・観測ログ</summary><pre id="at-log"></pre></details>`;
document.querySelector('.workspace').append(panel);
const worker=new Worker(new URL('./at-worker.mjs',import.meta.url),{type:'module'});let nextId=0,session=null,enc=null,pending=new Map(),observed=0,currentMap=null,fieldContext=null;
function candidateTables(){if(fieldContext){if(!fieldContext.resolved||!fieldContext.tableIds.length)throw Error('現在のノード・時間に対応するtable候補は未解決です');return fieldContext.tableIds;}return [Number($('at-table').value)];}
const message=(text,error=false)=>{$('at-message').textContent=text;$('at-message').classList.toggle('error',error);};
function send(type,args={}){return new Promise((resolve,reject)=>{const id=++nextId;pending.set(id,{resolve,reject});worker.postMessage({type,id,...args});});}
worker.onmessage=({data:m})=>{const p=pending.get(m.id);if(!p)return;pending.delete(m.id);if(!m.ok)p.reject(Error(m.error));else p.resolve(m.value);};worker.onerror=e=>{for(const p of pending.values())p.reject(Error(e.message));pending.clear();message(e.message,true);};
function show(s){session=s;$('at-bound').textContent=s.lowerBound;$('at-conditional').textContent=s.conditionalBound;$('at-state').textContent=s.initialSeed+' · 起動起点';$('at-save').disabled=false;$('at-identify-session').disabled=!s.events.some(e=>e.kind==='monster-observation');$('at-envelope').textContent=s.currentPositionEnvelope?`観測仮定下の現在位置候補: ${s.currentPositionEnvelope.intervals[0].first}以降 / 上限未確定 / 未解決区間 ${s.consumerUncertainty.length}件。直前の出現乱数位置とは別管理です。`:'';$('at-log').textContent=`全${s.events.length}件（表示は最新40件、保存は全件）\n`+JSON.stringify(s.events.slice(-40),null,2);try{localStorage.setItem('dq9-at-active-session',JSON.stringify(s));}catch{};}
function save(name,value){const u=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
const npcReplayPanel=attachNpcReplayPanel($('at-npc-replay'),{send,save});
window.addEventListener('dq9-rom-release',()=>npcReplayPanel.clear());
const run=f=>async()=>{try{await f();}catch(e){message(e.message,true);}};
$('at-start').onclick=run(async()=>{show(await send('start',{seed:$('at-seed').value}));observed=0;if(currentMap)show(await send('context',{map:currentMap}));message('既知seedを起点に開始しました。未証明消費は下限に加算しません。');});
$('at-unknown').onclick=run(async()=>{show(await send('unresolved-consumption',{observation:{id:'unknown:'+Date.now()+':'+(++observed),consumer:$('at-consumer').value,source:'human-observed-interval'}}));message('消費数未解決の区間を記録しました。0消費と確定せず、既知seedと証明済み下限を維持します。');});
$('at-save').onclick=()=>save('dq9-at-session.json',session);
$('at-identify-session').onclick=run(async()=>{if(!session)throw Error('追跡セッションを開始してください');try{storeSessionIdentification(session,sessionStorage);}catch(error){throw Error(`観測を引き渡せません: ${error.message}。追跡を保存し、条件付きAT探索でJSONを読み込んでください。`);}window.location.href=new URL('./at-identify.html?session=handoff',import.meta.url).href;});
$('at-search').onclick=run(async()=>{const target=$('at-target').value;if(!target)throw Error('対象モンスターを選択してください');candidateTables();const r=await send(fieldContext?'field-forecast':'forecast',{context:fieldContext,tableIds:candidateTables(),targets:target.split(',').map(Number),window:Number($('at-window').value),conditional:$('at-use-conditional').checked});$('at-forecast').replaceChildren();if(r.format==='dq9-natural-tail-forecast'){renderNaturalForecast(r);return;}for(const t of r.results){const title=document.createElement('p');title.textContent=`table ${t.tableId} · ${r.from}〜${r.through}`;$('at-forecast').append(title);const table=document.createElement('table');const header=document.createElement('tr');for(const s of ['AT位置','下限から','モンスター','乱数15bit']){const th=document.createElement('th');th.textContent=s;header.append(th);}table.append(header);for(const h of t.hits){const tr=document.createElement('tr');for(const s of [h.position,'+'+h.offset,h.monsterName,h.random]){const td=document.createElement('td');td.textContent=String(s);tr.append(td);}table.append(tr);}if(!t.hits.length){const p=document.createElement('p');p.textContent='この窓には候補なし。窓より先は除外しません。';$('at-forecast').append(p);}$('at-forecast').append(table);}message('対象になるweighted乱数位置です。現在位置の確定や「あと何フレーム」という保証ではありません。');});
function renderNaturalForecast(r){for(const s of r.scenarios){const p=document.createElement('p');p.textContent=`area ${s.areaMask} / time ${s.timeValue} / table候補 ${s.candidates.join(', ')}`;$('at-forecast').append(p);if(s.unavailableTables.length){const note=document.createElement('p');note.textContent=`既存分布なし: ${s.unavailableTables.join(', ')}。この候補は未解決のまま保持します。`;$('at-forecast').append(note);}const table=document.createElement('table'),head=document.createElement('tr');for(const label of ['table消費位置','monster消費位置','table','対象']){const th=document.createElement('th');th.textContent=label;head.append(th);}table.append(head);for(const hit of s.hits){const tr=document.createElement('tr');for(const value of [hit.tablePosition,hit.monsterPosition,hit.tableId,hit.monsterName]){const td=document.createElement('td');td.textContent=String(value);tr.append(td);}table.append(tr);}$('at-forecast').append(table);}message('表選択→monster選択まで到達した場合の連続2消費候補です。失敗試行・monster移動・フレーム数は別の未解決状態として保持しています。');}
function monsters(){let ids;try{ids=candidateTables();}catch{ids=[];}$('at-monster').replaceChildren();const seen=new Set();for(const id of ids)for(const m of enc?.[String(id)]?.data||[])if(!m.trapMonster&&!seen.has(m.monsterId)){seen.add(m.monsterId);$('at-monster').add(new Option(`${m.monsterId} · ${m.monsterName}`,m.monsterId));}}
$('at-table').onchange=()=>{fieldContext=null;$('at-context').textContent='手動table指定（ノード自動候補を解除）。実機の現在エリアとは未照合です。';monsters();};
window.addEventListener('dq9-field-context',e=>{fieldContext=e.detail;$('at-context').textContent=`map ${fieldContext.mapId??'未結合'} / node ${fieldContext.nodeId??'全候補'} / area ${fieldContext.areaMasks.join(', ')} / table候補 ${fieldContext.tableIds.join(', ')||'未解決'}。表示選択であり実機位置の証明ではありません。`;if(fieldContext.tableIds.length===1)$('at-table').value=fieldContext.tableIds[0];monsters();});
window.addEventListener('dq9-rom-release',()=>{fieldContext=null;currentMap=null;monsters();});
window.addEventListener('dq9-video-observation',e=>{if(session)send('video-observation',{observation:e.detail}).then(show).catch(error=>message(error.message,true));});
$('at-observe').onclick=run(async()=>{if(!$('at-monster').value)throw Error('観測monsterを選択してください');const tableIds=candidateTables();const id='human:'+Date.now()+':'+(++observed);show(await send('observe',{observation:{id,tableIds,monsterId:Number($('at-monster').value),source:'human-confirmation',naturalConfirmed:$('at-natural').checked},window:Number($('at-window').value)}));message(`観測分岐を更新しました。窓内候補 ${session.candidates.positions.length}件と未探索の先を保持。証明済み下限 ${session.lowerBound} は変更していません。`);});
$('at-trace').onchange=run(async()=>{const file=$('at-trace').files[0];if(!file)return;const trace=JSON.parse(await file.text());if(trace.format==='dq9-npc-replay-v1'){const r=await send('replay',{trace});$('at-replay').textContent=`NPC継続: ${r.resolved?'条件内で予測完了':'未解決境界で停止'} / 条件付き${r.conditionalConsumed} draw / 証明済み下限への加算0 / ${r.reason}。起動履歴は未証明、追跡セッションは変更していません。`;}else if(['dq9-at-observed-exec-series','dq9-nonspawn-actual-pairs'].includes(trace.format)){const r=await send('replay',{trace,context:fieldContext});$('at-replay').textContent=`実測replay: ${r.updates} AT / ${r.intCalls} ATRandInt / ${r.spawns.length}生成、差 ${r.mismatches.length}件。途中state起点なので起動下限へ加算しません。`;if(r.world)$('at-replay').textContent+=` 非spawn書き込み ${r.world.outputs.length}件 / 差 ${r.world.mismatches.length}件。経路到達と順序は観測入力です。`;if(r.scheduler)$('at-replay').textContent+=` scheduler ${r.scheduler.invocations}回 / 解決 ${r.scheduler.records.filter(x=>x.resolved).length}回 / 差 ${r.scheduler.mismatches.length}件。未入力の条件は推測しません。`;if(r.mismatches.length||r.scheduler?.mismatches.length)message(JSON.stringify([...r.mismatches,...(r.scheduler?.mismatches||[])]),true);}else{show(await send('boot-trace',{trace}));$('at-replay').textContent='外部既知seedから連続した起動exec prefixを照合しました。';}});
$('at-restore').onchange=run(async()=>{const f=$('at-restore').files[0];if(!f)return;const saved=JSON.parse(await f.text());if(saved.format!=='dq9-at-session')throw Error('追跡セッション形式ではありません');show(await send('restore',{saved}));$('at-seed').value=session.initialSeed;message('保存した証拠と観測を再評価して復元しました。');});
window.addEventListener('dq9-map-selection',e=>{currentMap=e.detail;$('at-context').textContent=`表示中 map ${currentMap.mapId} / ${currentMap.name} / ${currentMap.fieldCode}。表示選択は実機の現在map確定ではありません。`;if(session)send('context',{map:{...currentMap,source:'map-browser-selection'}}).then(show).catch(e=>message(e.message,true));});
fetch('./data/enc.json').then(r=>r.json()).then(data=>{enc=data.main;const metal=metalCatalog(enc);$('at-target').replaceChildren();$('at-target').add(new Option('全メタル系',Array.from(metal.keys()).join(',')));for(const [id,name] of metal)$('at-target').add(new Option(`${id} · ${name}`,String(id)));monsters();}).catch(e=>message(e.message,true));
