import {PRODUCTION_AT_INPUT_NOTICE,assertProductionATInput} from './production-at-input-policy.mjs?v=production-inputs-20261006-1320';
import {candidateForecastMarkup,mountCandidateForecastPanel} from './at-candidate-forecast-panel.mjs';
import {storeSessionIdentification} from './at-session-identification.mjs?v=production-inputs-20261006-1320';
import {attachNpcReplayPanel} from './npc-at-replay-panel.mjs?v=production-inputs-20261006-1320';
import {metalCatalog} from './monster-catalog.mjs';
const $=id=>document.getElementById(id);
const panel=document.createElement('section');panel.className='at-panel';panel.innerHTML=`<div class="at-heading"><h2>AT追跡・メタル候補</h2><span id="at-state">未開始</span></div><p class="muted">${PRODUCTION_AT_INPUT_NOTICE}</p><div class="at-controls"><label>既知initial seed <input id="at-seed" placeholder="0x12345678" autocomplete="off" spellcheck="false"></label><button id="at-start">起動から追跡開始</button><button id="at-save" disabled>追跡を保存</button><button id="at-identify-session" disabled>記録した観測から候補を絞る</button><label class="file-button">追跡を復元<input id="at-restore" type="file" accept=".json"></label></div><div class="at-metrics"><div><small>証明済み下限</small><strong id="at-bound">—</strong></div><div><small>観測仮定つき下限</small><strong id="at-conditional">—</strong></div><div><small>未探索の先</small><strong>候補を保持</strong></div></div><div class="at-controls"><label>table ID <input id="at-table" type="number" min="0" value="30"></label><label>探索窓 <input id="at-window" type="number" min="1" max="1000000" value="50000"></label><label>対象 <select id="at-target"><option value="">読込中</option></select></label><label><input id="at-use-conditional" type="checkbox">観測仮定の分岐を使う</label><button id="at-search">次の対象候補</button></div><div id="at-context" class="muted">現在のmap/areaは未接続。table IDは自動確定しません。</div><div class="at-controls"><label>観測monster <select id="at-monster"></select></label><label><input id="at-natural" type="checkbox">自然生成と確認</label><button id="at-observe">新しい出現を記録</button></div><div id="at-message" role="status">見えているmonsterだけでは自然生成経路・正しいエリア表は証明できません。観測仮定と証明済み下限を分けて保持します。</div><div id="at-envelope" class="muted"></div><div class="at-controls"><label>未解決の消費区間 <select id="at-consumer"><option value="NPC-movement">NPC移動</option><option value="pots-barrels">つぼ・たる</option><option value="map-entry">マップ入場・初期化</option><option value="unclassified">その他・不明</option></select></label><button id="at-unknown">区間を記録</button></div><div id="at-forecast"></div>${candidateForecastMarkup}<details><summary>DST・メモリ・実測traceはデバッグ専用</summary><p>${PRODUCTION_AT_INPUT_NOTICE}</p><p>このナビゲーターではDST・メモリ・実測traceの入力を受け付けません。</p><label class="file-button">trace JSONを読む<input id="at-trace" type="file" accept=".json" disabled></label><div id="at-replay"></div><section id="at-npc-replay"></section></details><details><summary>証拠・観測ログ</summary><pre id="at-log"></pre></details>`;
document.querySelector('.workspace').append(panel);
const worker=new Worker(new URL('./at-worker.mjs?v=symbolic-clock-20261009-e604633f',import.meta.url),{type:'module'});let nextId=0,session=null,enc=null,pending=new Map(),observed=0,currentMap=null,fieldContext=null;
function candidateTables(){if(fieldContext){if(!fieldContext.resolved||!fieldContext.tableIds.length)throw Error('現在のノード・時間に対応するtable候補は未解決です');return fieldContext.tableIds;}return [Number($('at-table').value)];}
const message=(text,error=false)=>{$('at-message').textContent=text;$('at-message').classList.toggle('error',error);};
function send(type,args={}){return new Promise((resolve,reject)=>{const id=++nextId;pending.set(id,{resolve,reject});worker.postMessage({type,id,...args});});}
worker.onmessage=({data:m})=>{const p=pending.get(m.id);if(!p)return;pending.delete(m.id);if(!m.ok)p.reject(Error(m.error));else p.resolve(m.value);};worker.onerror=e=>{for(const p of pending.values())p.reject(Error(e.message));pending.clear();message(e.message,true);};
// Bound the view before serialization. Native rows/source packets stay only in
// the complete session and its saved JSON, never in a multi-megabyte DOM node.
export function eventLogPreview(events){
 const text=v=>typeof v==='string'&&v.length>400?v.slice(0,400)+'…（全文は保存JSON）':v;
 const small=(v,depth=0)=>{if(v===null||typeof v!=='object')return text(v);if(depth>=3)return Array.isArray(v)?`[${v.length}件・保存JSON参照]`:'[詳細は保存JSON]';if(Array.isArray(v))return [...v.slice(0,8).map(x=>small(x,depth+1)),...(v.length>8?[`ほか${v.length-8}件`]:[])];return Object.fromEntries(Object.keys(v).slice(0,16).map(k=>[k,small(v[k],depth+1)]));};
 const pick=(o,keys)=>Object.fromEntries(keys.filter(k=>o&&Object.hasOwn(o,k)).map(k=>[k,small(o[k])]));
 const rows=events.slice(-40).map(event=>{
  const base=pick(event,['kind','id','conditionalBefore','conditionalAfter','provenLowerBound','observedLocalMinimum','linkedToLocalEpoch','bootProof','status']);
  if(event.kind==='map-entry-projection'||event.kind==='npc-entry-continuation'){
   const packet=event.packet??{},projection=event.projection??{},source=packet.source??{};
   return {...base,origin:pick(packet.origin,['epoch','frame','originFrame','mapId','seed','ramSha256']),source:pick(source,['mapId','fieldCode','romSha256']),instructionHashes:pick(source.instructionBinding,['armSha256','overlay17Sha256']),window:{...pick(packet.schedule,['originFrame','endFrame']),lastNpcSourceFrame:packet.clocks?.ticks?.at(-1)?.sourceFrame,clockTicks:packet.clocks?.ticks?.length},projection:pick(projection,['resolved','reason','seedBefore','seedAfter','conditionalConsumed','provedMinimumAT','maximumActualAT','bootProof','worldResolved','boundary','conditions','firstActualUnknown','unknownSuffix']),counts:{draws:projection.draws?.length,invocations:projection.invocations?.length,frames:projection.frames?.length,controllers:projection.controllers?.length,definitions:projection.membership?.definitions?.length}};
  }
  if(event.kind==='map-entry-observation'||event.kind==='npc-continuation-observation'){
   const evidence=event.evidence??{},comparison=event.comparison??{};
   return {...base,evidence:{...pick(evidence,['schema','epoch','startFrame','endFrame','originRamSha256']),closedRamSha256:evidence.stateWitness?.ramSha256,eventCount:evidence.events?.length,comparisonCount:evidence.comparisons?.length,drainCount:evidence.drains?.length,profileCount:evidence.profiles?.length},comparison:pick(comparison,['matches','orderedConsumptionMatches','firstDifference','differenceCount','checks','orderedPairs','observedMinimumLocalCalls','externalClockMatched','projectedActorFieldsMatch','seedBefore','seedAfter','bootProof','worldResolved','observer'])};
  }
  if(event.kind==='verified-boot-exec-prefix')return {...base,...pick(event,['count','finalSeed','source']),trace:{...pick(event.trace,['origin','initialSeed','startPosition']),updates:event.trace?.updates?.length}};
  return small(event);
 });
 return `全${events.length}件（表示は最新40件の要約。raw trace・source・全比較は「追跡を保存」のJSONに保持）\n`+JSON.stringify(rows,null,2);
}
function show(s){const local=s.origin==='known-local-checkpoint';session=s;candidateForecast.invalidate();$('at-bound').textContent=s.lowerBound;$('at-conditional').textContent=s.conditionalBound;$('at-state').textContent=s.initialSeed+(local?' · 既知局所checkpoint起点（起動証明なし）':' · 起動起点');$('at-save').disabled=false;$('at-identify-session').disabled=local||!s.events.some(e=>e.kind==='monster-observation');$('at-identify-session').title=local?'局所checkpointの記録は起動seed前提の候補絞り込みへ渡せません':'';$('at-envelope').textContent=s.currentPositionEnvelope?`${local?'局所起点からの条件付き消費位置候補':'観測仮定下の現在位置候補'}: ${s.currentPositionEnvelope.intervals[0].first}以降 / 上限未確定 / 未解決区間 ${s.consumerUncertainty.length}件。直前の出現乱数位置とは別管理です。`:'';$('at-log').textContent=eventLogPreview(s.events);try{localStorage.setItem('dq9-at-active-session',JSON.stringify(s));}catch{};}
function save(name,value){const u=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
const candidateForecast=mountCandidateForecastPanel({document,send,getSession:()=>session,getContext:()=>fieldContext,getTarget:()=>$('at-target').value,getWindow:()=>$('at-window').value});
for(const id of ['at-target','at-window','at-seed'])for(const event of ['input','change'])$(id).addEventListener(event,()=>candidateForecast.invalidate());
window.addEventListener('pageshow',()=>{candidateForecast.invalidate();candidateForecast.checkStorage();});
candidateForecast.checkStorage();
const npcReplayPanel=attachNpcReplayPanel($('at-npc-replay'),{send,save});
window.addEventListener('dq9-rom-release',()=>npcReplayPanel.clear());
const run=f=>async()=>{try{await f();}catch(e){message(e.message,true);}};
$('at-start').onclick=run(async()=>{show(await send('start',{seed:$('at-seed').value}));observed=0;if(currentMap)show(await send('context',{map:currentMap}));message('既知seedを起点に開始しました。未証明消費は下限に加算しません。');});
$('at-unknown').onclick=run(async()=>{show(await send('unresolved-consumption',{observation:{id:'unknown:'+Date.now()+':'+(++observed),consumer:$('at-consumer').value,source:'human-observed-interval'}}));message('消費数未解決の区間を記録しました。0消費と確定せず、既知seedと証明済み下限を維持します。');});
$('at-save').onclick=()=>save('dq9-at-session.json',session);
$('at-identify-session').onclick=run(async()=>{if(!session)throw Error('追跡セッションを開始してください');if(session.origin==='known-local-checkpoint')throw Error('局所checkpointの記録は起動seed前提の候補絞り込みへ渡せません。起動履歴の証明には変換しません。');try{storeSessionIdentification(session,sessionStorage);}catch(error){throw Error(`観測を引き渡せません: ${error.message}。追跡を保存し、条件付きAT探索でJSONを読み込んでください。`);}window.location.href=new URL('./at-identify.html',import.meta.url).href;});
$('at-search').onclick=run(async()=>{const target=$('at-target').value;if(!target)throw Error('対象モンスターを選択してください');candidateTables();const r=await send(fieldContext?'field-forecast':'forecast',{context:fieldContext,tableIds:candidateTables(),targets:target.split(',').map(Number),window:Number($('at-window').value),conditional:$('at-use-conditional').checked});$('at-forecast').replaceChildren();if(r.format==='dq9-natural-tail-forecast'){renderNaturalForecast(r);return;}for(const t of r.results){const title=document.createElement('p');title.textContent=`table ${t.tableId} · ${r.from}〜${r.through}`;$('at-forecast').append(title);const table=document.createElement('table');const header=document.createElement('tr');for(const s of ['AT位置','下限から','モンスター','乱数15bit']){const th=document.createElement('th');th.textContent=s;header.append(th);}table.append(header);for(const h of t.hits){const tr=document.createElement('tr');for(const s of [h.position,'+'+h.offset,h.monsterName,h.random]){const td=document.createElement('td');td.textContent=String(s);tr.append(td);}table.append(tr);}if(!t.hits.length){const p=document.createElement('p');p.textContent='この窓には候補なし。窓より先は除外しません。';$('at-forecast').append(p);}$('at-forecast').append(table);}message('対象になるweighted乱数位置です。現在位置の確定や「あと何フレーム」という保証ではありません。');});
function renderNaturalForecast(r){for(const s of r.scenarios){const p=document.createElement('p');p.textContent=`area ${s.areaMask} / time ${s.timeValue} / table候補 ${s.candidates.join(', ')}`;$('at-forecast').append(p);if(s.unavailableTables.length){const note=document.createElement('p');note.textContent=`既存分布なし: ${s.unavailableTables.join(', ')}。この候補は未解決のまま保持します。`;$('at-forecast').append(note);}const table=document.createElement('table'),head=document.createElement('tr');for(const label of ['table消費位置','monster消費位置','table','対象']){const th=document.createElement('th');th.textContent=label;head.append(th);}table.append(head);for(const hit of s.hits){const tr=document.createElement('tr');for(const value of [hit.tablePosition,hit.monsterPosition,hit.tableId,hit.monsterName]){const td=document.createElement('td');td.textContent=String(value);tr.append(td);}table.append(tr);}$('at-forecast').append(table);}message('表選択→monster選択まで到達した場合の連続2消費候補です。失敗試行・monster移動・フレーム数は別の未解決状態として保持しています。');}
function monsters(){let ids;try{ids=candidateTables();}catch{ids=[];}$('at-monster').replaceChildren();const seen=new Set();for(const id of ids)for(const m of enc?.[String(id)]?.data||[])if(!m.trapMonster&&!seen.has(m.monsterId)){seen.add(m.monsterId);$('at-monster').add(new Option(`${m.monsterId} · ${m.monsterName}`,m.monsterId));}}
$('at-table').onchange=()=>{fieldContext=null;candidateForecast.invalidate();$('at-context').textContent='手動table指定（ノード自動候補を解除）。実機の現在エリアとは未照合です。';monsters();};
window.addEventListener('dq9-field-context',e=>{fieldContext=e.detail;candidateForecast.invalidate();$('at-context').textContent=`map ${fieldContext.mapId??'未結合'} / node ${fieldContext.nodeId??'全候補'} / area ${fieldContext.areaMasks.join(', ')} / table候補 ${fieldContext.tableIds.join(', ')||'未解決'}。表示選択であり実機位置の証明ではありません。`;if(fieldContext.tableIds.length===1)$('at-table').value=fieldContext.tableIds[0];monsters();});
window.addEventListener('dq9-rom-release',()=>{fieldContext=null;currentMap=null;candidateForecast.invalidate();monsters();});
window.addEventListener('dq9-video-observation',e=>{if(session)send('video-observation',{observation:e.detail}).then(show).catch(error=>message(error.message,true));});
$('at-observe').onclick=run(async()=>{if(!$('at-monster').value)throw Error('観測monsterを選択してください');const tableIds=candidateTables();const id='human:'+Date.now()+':'+(++observed);show(await send('observe',{observation:{id,tableIds,monsterId:Number($('at-monster').value),source:'human-confirmation',naturalConfirmed:$('at-natural').checked},window:Number($('at-window').value)}));message(`観測分岐を更新しました。窓内候補 ${session.candidates.positions.length}件と未探索の先を保持。証明済み下限 ${session.lowerBound} は変更していません。`);});
$('at-trace').onchange=run(async()=>{throw Error(PRODUCTION_AT_INPUT_NOTICE);});
$('at-restore').onchange=run(async()=>{const f=$('at-restore').files[0];if(!f)return;const saved=JSON.parse(await f.text());assertProductionATInput(saved);if(saved.format!=='dq9-at-session')throw Error('追跡セッション形式ではありません');show(await send('restore',{saved}));$('at-seed').value=session.initialSeed;message(session.origin==='known-local-checkpoint'?'局所checkpointからの条件付き消費を復元しました。起動履歴は未証明で、起動seed前提の候補絞り込みには渡せません。':'保存した証拠と観測を再評価して復元しました。');});
window.addEventListener('dq9-map-selection',e=>{currentMap=e.detail;candidateForecast.invalidate();$('at-context').textContent=`表示中 map ${currentMap.mapId} / ${currentMap.name} / ${currentMap.fieldCode}。表示選択は実機の現在map確定ではありません。`;if(session)send('context',{map:{...currentMap,source:'map-browser-selection'}}).then(show).catch(e=>message(e.message,true));});
fetch('./data/enc.json').then(r=>r.json()).then(data=>{enc=data.main;const metal=metalCatalog(enc);$('at-target').replaceChildren();$('at-target').add(new Option('全メタル系',Array.from(metal.keys()).join(',')));for(const [id,name] of metal)$('at-target').add(new Option(`${id} · ${name}`,String(id)));monsters();}).catch(e=>message(e.message,true));
