const $=id=>document.getElementById(id);
const panel=document.createElement('section');panel.className='at-panel';panel.innerHTML=`<div class="at-heading"><h2>AT追跡・メタル候補</h2><span id="at-state">未開始</span></div><div class="at-controls"><label>既知initial seed <input id="at-seed" placeholder="0x12345678" autocomplete="off" spellcheck="false"></label><button id="at-start">起動から追跡開始</button><button id="at-save" disabled>追跡を保存</button><label class="file-button">追跡を復元<input id="at-restore" type="file" accept=".json"></label></div><div class="at-metrics"><div><small>証明済み下限</small><strong id="at-bound">—</strong></div><div><small>観測仮定つき下限</small><strong id="at-conditional">—</strong></div><div><small>未探索の先</small><strong>候補を保持</strong></div></div><div class="at-controls"><label>table ID <input id="at-table" type="number" min="0" value="30"></label><label>探索窓 <input id="at-window" type="number" min="1" max="1000000" value="50000"></label><label>対象 <select id="at-target"><option value="">読込中</option></select></label><label><input id="at-use-conditional" type="checkbox">観測仮定の分岐を使う</label><button id="at-search">次の対象候補</button></div><div id="at-context" class="muted">現在のmap/areaは未接続。table IDは自動確定しません。</div><div class="at-controls"><label>観測monster <select id="at-monster"></select></label><label><input id="at-natural" type="checkbox">自然生成と確認</label><button id="at-observe">新しい出現を記録</button></div><div id="at-message" role="status">見えているmonsterだけでは自然生成経路・正しいエリア表は証明できません。観測仮定と証明済み下限を分けて保持します。</div><div id="at-forecast"></div><details><summary>起動連続trace / 実測replay</summary><label class="file-button">trace JSONを読む<input id="at-trace" type="file" accept=".json"></label><div id="at-replay"></div></details><details><summary>証拠・観測ログ</summary><pre id="at-log"></pre></details>`;
document.querySelector('.workspace').append(panel);
const worker=new Worker(new URL('./at-worker.mjs',import.meta.url),{type:'module'});let nextId=0,session=null,enc=null,pending=new Map(),observed=0,currentMap=null;
const message=(text,error=false)=>{$('at-message').textContent=text;$('at-message').classList.toggle('error',error);};
function send(type,args={}){return new Promise((resolve,reject)=>{const id=++nextId;pending.set(id,{resolve,reject});worker.postMessage({type,id,...args});});}
worker.onmessage=({data:m})=>{const p=pending.get(m.id);if(!p)return;pending.delete(m.id);if(!m.ok)p.reject(Error(m.error));else p.resolve(m.value);};worker.onerror=e=>{for(const p of pending.values())p.reject(Error(e.message));pending.clear();message(e.message,true);};
function show(s){session=s;$('at-bound').textContent=s.lowerBound;$('at-conditional').textContent=s.conditionalBound;$('at-state').textContent=s.initialSeed+' · 起動起点';$('at-save').disabled=false;$('at-log').textContent=JSON.stringify(s.events,null,2);try{localStorage.setItem('dq9-at-active-session',JSON.stringify(s));}catch{};}
function save(name,value){const u=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
const run=f=>async()=>{try{await f();}catch(e){message(e.message,true);}};
$('at-start').onclick=run(async()=>{show(await send('start',{seed:$('at-seed').value}));observed=0;if(currentMap)show(await send('context',{map:currentMap}));message('既知seedを起点に開始しました。未証明消費は下限に加算しません。');});
$('at-save').onclick=()=>save('dq9-at-session.json',session);
$('at-search').onclick=run(async()=>{const target=$('at-target').value;if(!target)throw Error('対象モンスターを選択してください');const r=await send('forecast',{tableIds:[Number($('at-table').value)],targets:target.split(',').map(Number),window:Number($('at-window').value),conditional:$('at-use-conditional').checked});$('at-forecast').replaceChildren();for(const t of r.results){const title=document.createElement('p');title.textContent=`table ${t.tableId} · ${r.from}〜${r.through}`;$('at-forecast').append(title);const table=document.createElement('table');const header=document.createElement('tr');for(const s of ['AT位置','下限から','モンスター','乱数15bit']){const th=document.createElement('th');th.textContent=s;header.append(th);}table.append(header);for(const h of t.hits){const tr=document.createElement('tr');for(const s of [h.position,'+'+h.offset,h.monsterName,h.random]){const td=document.createElement('td');td.textContent=String(s);tr.append(td);}table.append(tr);}if(!t.hits.length){const p=document.createElement('p');p.textContent='この窓には候補なし。窓より先は除外しません。';$('at-forecast').append(p);}$('at-forecast').append(table);}message('対象になるweighted乱数位置です。現在位置の確定や「あと何フレーム」という保証ではありません。');});
function monsters(){const t=enc?.[String(Number($('at-table').value))];$('at-monster').replaceChildren();for(const m of t?.data||[])if(!m.trapMonster)$('at-monster').add(new Option(`${m.monsterId} · ${m.monsterName}`,m.monsterId));}
$('at-table').onchange=monsters;
$('at-observe').onclick=run(async()=>{if(!$('at-monster').value)throw Error('観測monsterを選択してください');const id='human:'+Date.now()+':'+(++observed);show(await send('observe',{observation:{id,tableId:Number($('at-table').value),monsterId:Number($('at-monster').value),source:'human-confirmation',naturalConfirmed:$('at-natural').checked},window:Number($('at-window').value)}));message(`観測分岐を更新しました。窓内候補 ${session.candidates.positions.length}件と未探索の先を保持。証明済み下限 ${session.lowerBound} は変更していません。`);});
$('at-trace').onchange=run(async()=>{const file=$('at-trace').files[0];if(!file)return;const trace=JSON.parse(await file.text());if(trace.format==='dq9-at-observed-exec-series'){const r=await send('replay',{trace});$('at-replay').textContent=`実測replay: ${r.updates} AT / ${r.intCalls} ATRandInt / ${r.spawns.length}生成、差 ${r.mismatches.length}件。途中state起点なので起動下限へ加算しません。`;if(r.mismatches.length)message(JSON.stringify(r.mismatches),true);}else{show(await send('boot-trace',{trace}));$('at-replay').textContent='外部既知seedから連続した起動exec prefixを照合しました。';}});
$('at-restore').onchange=run(async()=>{const f=$('at-restore').files[0];if(!f)return;const saved=JSON.parse(await f.text());if(saved.format!=='dq9-at-session')throw Error('追跡セッション形式ではありません');show(await send('restore',{saved}));$('at-seed').value=session.initialSeed;message('保存した証拠と観測を再評価して復元しました。');});
window.addEventListener('dq9-map-selection',e=>{currentMap=e.detail;$('at-context').textContent=`表示中 map ${currentMap.mapId} / ${currentMap.name} / ${currentMap.fieldCode}。表示選択は実機の現在map確定ではありません。`;if(session)send('context',{map:{...currentMap,source:'map-browser-selection'}}).then(show).catch(e=>message(e.message,true));});
fetch('./data/enc.json').then(r=>r.json()).then(data=>{enc=data.main;const metal=new Map();for(const t of Object.values(enc))for(const m of t.data||[])if(/^(メタルスライム|はぐれメタル|メタルキング|プラチナキング)$/.test(m.monsterName)&&!m.trapMonster)metal.set(Number(m.monsterId),m.monsterName);$('at-target').replaceChildren();$('at-target').add(new Option('全メタル系',Array.from(metal.keys()).join(',')));for(const [id,name] of metal)$('at-target').add(new Option(`${id} · ${name}`,String(id)));monsters();}).catch(e=>message(e.message,true));
