// Conditional, source-carried F06 creator return. No future allocation, actor,
// seed or creation result is accepted. Logical addresses are internal identities,
// never claims about native allocation addresses. Stops before hero/body update.
import {mineCreatorResources} from './monster-creation-resources.mjs';
import {projectMonsterCreation} from './monster-creation.mjs';
import {decodeEncounterStream} from './encounter-distribution.mjs';
import {decodeCalls} from './map-core.mjs';
import {Narc} from './vendor/narc-source.js';
import {BufferReader,Compression} from './vendor/nitro-fs.mjs';
import {inspectMonsterModel} from './monster-geometry.mjs';
import './vendor/gp2.js';
const need=(p,m)=>{if(!p)throw Error(m);},uint=(n,max=0xffffffff)=>Number.isInteger(n)&&n>=0&&n<=max;
const exact=(o,keys)=>o&&typeof o==='object'&&!Array.isArray(o)&&Object.keys(o).length===keys.length&&keys.every(k=>Object.hasOwn(o,k));
const dense=a=>Array.isArray(a)&&Array.from({length:a.length},(_,i)=>Object.hasOwn(a,i)).every(Boolean);
export const F06_CREATOR_CONDITIONS=['ordinaryF06TemplateConstructor','successfulModelAndAIAllocations','successfulTemplateAndComponentAllocations','successfulSharedModelBinding','requiredTemplateConfigAndDescriptorAllocationsSucceeded','stableCreatorDescriptorsAndSerialWriters','distinctSimultaneousLiveLeafAllocations','noOverlappingReuse','graphicsCallbacksConfinedToVisualStorage','samePoolHeapStorageAcrossResets','unchangedHeapFillPolicy','poolFirstPositiveAllocationAfterReset','noInterveningPoolAliasWrites'];
const heapKeys=['descriptorPointer','heapPointer','vtable','heapArgument','alignment','signature','payloadBegin','payloadEnd','controlWord'];
export function validateF06CreatorPacket(packet,initialSourceFrame){
 need(exact(packet,['schema','initialSourceFrame','initialHeap','conditions','provenance'])&&packet.schema==='dq9-f06-creator-v1'&&packet.initialSourceFrame===initialSourceFrame,'Original-frame source creator packet required');
 need(exact(packet.provenance,['kind','sourceFrame'])&&packet.provenance.kind==='source-constructor-conditions'&&packet.provenance.sourceFrame===initialSourceFrame,'Source-constructor provenance required');
 need(exact(packet.conditions,F06_CREATOR_CONDITIONS)&&F06_CREATOR_CONDITIONS.every(k=>[true,false,null].includes(packet.conditions[k])),'Every creator condition must be explicitly true, false or unknown');
 const h=packet.initialHeap;need(exact(h,heapKeys)&&heapKeys.every(k=>uint(h[k])),'Complete original pool heap words required');
 need(h.heapPointer>=0x02000000&&h.heapPointer<0x02400000&&h.payloadBegin===h.heapPointer+0x30&&h.payloadEnd<=0x02400000&&h.payloadEnd>=h.payloadBegin+0x1320&&h.descriptorPointer>=0x020000d8&&h.descriptorPointer<0x02400000&&h.vtable===0x020e9274&&h.heapArgument===h.heapPointer&&h.alignment===4&&h.signature===0x46524d48,'Unsupported source pool heap layout');
 return structuredClone(packet);
}
export function prepareF06Creator(project,rom,packet,initialSourceFrame){return {packet:validateF06CreatorPacket(packet,initialSourceFrame),project,rom,templates:new Map(),sourceWorldResolved:false};}
export function bindF06CreatorOrigin(plan,context){
 if(!plan)return;const h=plan.packet.initialHeap;need(h.descriptorPointer===context.controllerPointer+0xd8,'Creator heap descriptor differs from original controller');for(let i=0;i<12;i++){const slot=context.inventory?.slots?.find(s=>s.slot===112+i);need(slot?.registryKnown===true&&slot.pointer===h.payloadBegin+i*0x198&&uint(slot.e0Byte,255),'Creator heap differs from original contiguous pool');}plan.originBinding=true;
}
export function canCarryF06PoolStorage(plan,controllerPointer,allocationPointer){
 if(!plan?.originBinding)return false;const {initialHeap:h,conditions:c}=plan.packet;
 return h.descriptorPointer===controllerPointer+0xd8&&allocationPointer===h.payloadBegin&&(h.controlWord&1)===0&&['samePoolHeapStorageAcrossResets','unchangedHeapFillPolicy','poolFirstPositiveAllocationAfterReset','noInterveningPoolAliasWrites'].every(k=>c[k]===true);
}
export function convertCreatorScale(argument){
 need(argument&&[1,2].includes(argument.type)&&Number.isFinite(argument.value),'Numeric source encounter scale required');let value;
 if(argument.type===1){need(Number.isInteger(argument.value)&&argument.value>=-2147483648&&argument.value<=2147483647,'Integer scale domain');value=argument.value<<12;}
 else{value=Math.trunc(Math.fround(Math.fround(argument.value)*4096));need(value>=-2147483648&&value<=2147483647,'Float scale conversion outside signed32');}
 const result=(value<<16)>>16;return result===0?4096:result;
}
// Same header-directed BLZ interpretation as the existing ROM trig reader.
export function sourceArm9(input){
 const rom=input instanceof Uint8Array?input:new Uint8Array(input),v=new DataView(rom.buffer,rom.byteOffset,rom.byteLength);need(rom.length>=512&&String.fromCharCode(...rom.subarray(12,16))==='YDQJ'&&rom[30]===0,'JP revision0 source required');
 const offset=v.getUint32(32,true),base=v.getUint32(40,true),size=v.getUint32(44,true);need(base===0x02000000&&size>=8&&offset+size<=rom.length,'ARM9 source extent');const raw=rom.subarray(offset,offset+size),r=new DataView(raw.buffer,raw.byteOffset,raw.byteLength),po=v.getUint32(0x70,true)-base-4;need(po>=0&&po+4<=size,'Module pointer extent');const settings=r.getUint32(po,true)-base;need(settings>=0&&settings+24<=size,'Module settings extent');let decoded=raw;
 const end=r.getUint32(settings+20,true);if(end){need(end===base+size,'Compressed ARM9 end');const word=r.getUint32(size-8,true),span=word&0xffffff,header=word>>>24,extra=r.getUint32(size-4,true);need(header>=8&&header<=span&&span<=size&&extra>0&&size+extra<=0x2000000,'BLZ extent');need(raw.subarray(size-header,size-8).every(b=>b===255),'BLZ padding');decoded=new Uint8Array(size+extra);decoded.set(raw);let src=size-header,dst=decoded.length,prefix=size-span;while(dst>prefix){need(--src>=prefix,'BLZ flags');const flags=raw[src];for(let bit=7;bit>=0&&dst>prefix;bit--){if(flags&(1<<bit)){need(src-2>=prefix,'BLZ reference');const a=raw[--src],b=raw[--src],count=(a>>>4)+3,distance=((a&15)<<8|b)+3;need(dst-count>=prefix,'BLZ output');for(let i=0;i<count;i++){--dst;need(dst+distance<decoded.length,'BLZ prefix');decoded[dst]=decoded[dst+distance];}}else{need(--src>=prefix,'BLZ literal');decoded[--dst]=raw[src];}}}need(src===prefix,'BLZ remaining bytes');}
 const d=new DataView(decoded.buffer,decoded.byteOffset,decoded.byteLength),range=(a,n)=>{need(uint(a)&&a>=base&&a-base+n<=decoded.length,'Source literal outside ARM9');return a-base;};return{u8:a=>d.getUint8(range(a,1)),u32:a=>d.getUint32(range(a,4),true),text:a=>{let p=range(a,1),end=p;while(end<decoded.length&&decoded[end]&&end-p<64)end++;need(end<decoded.length&&decoded[end]===0,'Source name termination');return String.fromCharCode(...decoded.subarray(p,end));}};
}
export function sourceF06KeyboardAngles(rom){
 const a=sourceArm9(rom),table=a.u32(0x02037f50);
 // JP ordinary cardinal readers, their branch-to-direction-byte mapping, and
 // the ROM table are bound together. No headings are taken from native futures.
 const rows=[['Up',0x02012134,0x40,0x02037c70,0xebff692f,8],['Down',0x02012148,0x80,0x02037c8c,0xebff692d,9],['Left',0x0201210c,0x20,0x02037ca8,0xebff6917,10],['Right',0x02012120,0x10,0x02037cc4,0xebff6915,11]];
 for(const [,reader,mask,call,bl,code] of rows){
  need([0xe1d000b0,0xe3100000|mask,0x13a00001,0x03a00000,0xe12fff1e].every((word,i)=>a.u32(reader+i*4)===(word>>>0)),'Unsupported keyboard reader source');
  need(a.u32(call)===bl&&a.u32(call+4)===0xe3500000&&a.u32(call+8)===(0x13a00000|code)&&a.u32(call+12)===0x15c40244,'Unsupported cardinal direction-byte source');
 }
 const Up=a.u32(table)|0,Down=a.u32(table+4)|0,Left=a.u32(table+8)|0,Right=a.u32(table+12)|0;
 need(Up===12868&&Down===0&&Left===19302&&Right===6434,'Unsupported ordinary cardinal direction table');
 return {Down,Right,Up,Left};
}
export function sourceCreatorMode(rom){const a=sourceArm9(rom),selector=a.u8(a.u32(0x0203394c)+5*13),flags=a.u32(a.u32(0x02033808)+selector*4),name=a.text(a.u32(a.u32(0x0203381c)+selector*4));need(selector>0&&selector<12&&flags===1&&name==='appear'&&a.u32(0x02035e08)===0xfffffe01,'Unsupported creator mode5/config selector');return{mode:5,c0:0,selector,name,flags,componentTag:{knownMask:0x1ff,value:1},runtimeAnimationObject:'null-or-owned-unresolved'};}
export function decodeCreatorConfig(bytes){
 need(bytes instanceof Uint8Array&&bytes.length>=16&&bytes.length<=65536,'Bounded template config required');const d=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength),u32=o=>d.getUint32(o,true),count=u32(0),pool=u32(4),poolSize=u32(8);need(u32(12)===4&&count>0&&count<=128&&pool>=16&&pool<=bytes.length&&poolSize<=bytes.length-pool&&bytes.length-pool-poolSize<16,'Config header/version');let at=16;for(let i=0;i<count;i++){need(at+4<=pool,'Config command header');const n=bytes[at+2],h=(3+Math.ceil(n/4)+3)&~3;need(at+h+4*n<=pool,'Config argument bounds');for(let j=0;j<n;j++){const type=(bytes[at+3+(j>>2)]>>>((j&3)*2))&3,raw=u32(at+h+j*4);need(type<=2,'Config argument type');if(type===0){need(raw<poolSize,'Config string offset');let e=pool+raw;while(e<pool+poolSize&&bytes[e])e++;need(e<pool+poolSize,'Config string termination');}if(type===2)need(Number.isFinite(d.getFloat32(at+h+j*4,true)),'Config finite float');}at+=h+n*4;}
 need(pool-at<16&&bytes.subarray(at,pool).every(x=>x===255)&&bytes.subarray(pool+poolSize).every(x=>x===255),'Config padding');const calls=decodeCalls(bytes);need(calls.length===count&&calls[0].opcode===100&&calls[0].argumentCount===1&&calls[0].args[0].type===1,'Config capacity command');const capacity=calls[0].values[0];need(uint(capacity,80)&&capacity>0,'Config capacity');const rows=[];let ended=false;
 for(const c of calls.slice(1)){if(c.opcode===102){need(!ended&&c.argumentCount===4&&c.args[0].type===0&&c.args.slice(1).every(a=>a.type===2)&&typeof c.values[0]==='string'&&/^[A-Za-z0-9_]{1,15}$/.test(c.values[0])&&c.values.slice(1).every(v=>Number.isFinite(v)&&Math.fround(v*4096)>=-2147483648&&Math.fround(v*4096)<=2147483647),'Config row');need(!rows.some(r=>r.name===c.values[0]),'Duplicate config name');rows.push({index:rows.length,name:c.values[0],sourceOffset:c.offset});}else if(c.opcode===101){need(!ended&&c.argumentCount===0,'Config end marker');ended=true;}else{need(ended&&c.opcode===112&&c.argumentCount===1&&c.args[0].type===1&&c.values[0]===-1,'Unsupported config operation');}}
 need(ended&&rows.length===capacity,'Complete source config allocation required');return{capacity,rows};
}
function fieldModelName(nitro,record){const bytes=new Uint8Array(nitro.readFile('data/prm/mons_data2.nat')),d=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength),count=d.getUint32(0,true)&4095,pool=4+count*20,offset=d.getInt32(record.sourceOffset+4,true);need(offset>=0&&pool+offset<bytes.length,'Source field model name absent');let end=pool+offset;while(end<bytes.length&&bytes[end])end++;need(end<bytes.length,'Field name terminator');const name=String.fromCharCode(...bytes.subarray(pool+offset,end));need(/^z[0-9]{3}[a-z0-9]$/.test(name),'Unsupported field model key');return name;}
function sourceTemplate(plan,model){
 const key=fieldModelName(plan.project.nitro,model),stem=key+'_f',archive=new Uint8Array(plan.project.nitro.readFile('data/pack_lv5/enemy.gp2')),members=(need(archive.length<=128*1024*1024,'Bounded field archive required'),globalThis.NdsFontGp2.parseGp2(archive,new Set([stem+'.mon'])));need(members.length===1&&members[0].path===stem+'.mon','Unique ordinary field variant required');need(members[0].data.length<=8*1024*1024,'Bounded outer template required');const outer=Narc.load(members[0].data),outerNames=outer.files.map((_,i)=>outer.fnt.getFilenameOf(i));need(new Set(outerNames).size===outerNames.length&&outerNames.filter(n=>n?.includes('.cchr')).length===1,'Ambiguous compressed template member');const cchr=outer.getFile(stem+'.cchr');need(cchr?.[0]===16&&cchr.length>=4,'Field compressed container absent');const declared=cchr[1]|cchr[2]<<8|cchr[3]<<16;need(declared>=16&&declared<=8*1024*1024,'Bounded expanded template required');const expanded=Compression.decompress(new BufferReader(cchr.buffer,cchr.byteOffset,cchr.byteLength));need(expanded.length<=8*1024*1024,'Template allocation bound');const inner=Narc.load(expanded),innerNames=inner.files.map((_,i)=>inner.fnt.getFilenameOf(i));need(innerNames.every(n=>typeof n==='string')&&new Set(innerNames).size===innerNames.length&&innerNames.filter(n=>n.includes('.bcfg')).length===1&&innerNames.filter(n=>n.includes('.nsbmd')).length===1,'Ambiguous template config/model members');const configBytes=inner.getFile(stem+'.bcfg'),modelBytes=inner.getFile(stem+'.nsbmd');need(configBytes&&modelBytes,'Required config/model member absent');const config=decodeCreatorConfig(configBytes),mode=sourceCreatorMode(plan.rom);const selected=config.rows.find(r=>r.name===mode.name);need(selected,'Source mode config missing');
 for(const row of config.rows){const bytes=inner.getFile(row.name+'.nsbca');need(bytes&&bytes.length>=20&&String.fromCharCode(...bytes.subarray(0,4))==='BCA0','Required row descriptor resource missing');const v=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength);need(v.getUint32(8,true)===bytes.length,'Animation resource extent');for(const ext of ['nsbma','nsbtp','nsbta'])need(!inner.getFile(row.name+'.'+ext),'Additional animation descriptor family unsupported');}
 need(innerNames.every(n=>n===stem+'.bcfg'||n===stem+'.nsbmd'||config.rows.some(r=>n===r.name+'.nsbca')),'Additional template member outside bounded constructor');
 const parsed=inspectMonsterModel(modelBytes),m=parsed.modelOffset,r=parsed.r,mat=m+r.u32(m+8),count=r.u8(m+24),entryOffset=r.u16(mat+10);need(count===r.u8(mat+5)&&r.u16(mat+4+entryOffset)===4,'Material dictionary shape');const records=Array.from({length:count},(_,index)=>{const entry=mat+8+entryOffset+index*4,relativeMaterialOffset=r.u32(entry),start=mat+relativeMaterialOffset,size=r.u16(start+2);need(size>=16&&start>=mat&&(start&3)===0&&(relativeMaterialOffset&3)===0&&start+size<=parsed.modelEnd,'Material record range');r.range(start+12,4);return{index,relativeMaterialOffset,entryOffset:entry,alphaOffset:start+12,recordStart:start,recordSize:size};});need(new Set(records.map(r=>r.alphaOffset)).size===records.length&&records.every((a,i)=>records.every((b,j)=>i===j||a.recordStart+a.recordSize<=b.recordStart||b.recordStart+b.recordSize<=a.recordStart)),'Aliased material records');
 return{key,config,mode,selectedIndex:selected.index,modelBytesLength:modelBytes.length,modelOffset:m,materialOffset:mat,geometryCount:count,entryOffset,records,modelMemberOffset:modelBytes.byteOffset-expanded.byteOffset,expandedBytes:expanded.length};
}
export function projectF06Creator(session,request){
 const unknown=reason=>({resolved:false,created:false,reason,atConsumed:0,worldStepResolved:false});
 try{const plan=session.f06Continuation?.creator;need(plan&&session.f06Continuation.motion,'Source F06 creator and motion plans required');const{packet}=plan;for(const name of F06_CREATOR_CONDITIONS)need(packet.conditions[name]===true,'F06 creator condition unresolved: '+name);need(canCarryF06PoolStorage(plan,session.context.controllerPointer,packet.initialHeap.payloadBegin),'Original non-fill heap carry unavailable');need(session.currentMapId===20006&&request.mapId===20006,'F06-only creator path');
 const slots=session.context.inventory.slots;for(let i=0;i<12;i++){const s=slots.find(s=>s.slot===112+i);need(s?.pointer===packet.initialHeap.payloadBegin+i*0x198&&uint(s.e0Byte,255),'Complete same-storage pool byte carry required');}
 const mined=mineCreatorResources(plan.project.nitro,20006),model=mined.models.find(r=>r.speciesKey===request.species);need(model,'Selected source model absent');const key=model.speciesKey;let template=plan.templates.get(key);if(!template){template=sourceTemplate(plan,model);plan.templates.set(key,template);}
 const fields=structuredClone(session.context.fields),field=fields[0];need(field.mapId===20006&&field.index===0,'Carried field0 required');const modelBase=0x10000000,aiBase=0x10001000,templateBase=0x10002000,modelPointer=0x10004000,component=0x10005000,container=0x11000000,geometryPointer=container+template.modelMemberOffset+template.modelOffset,materialBlockPointer=container+template.modelMemberOffset+template.materialOffset;
 field.resources={models:{containerPointer:field.pointer+0x2f4,basePointer:modelBase,declaredCount:mined.models.length,entries:mined.models.map((r,index)=>({...r,index,pointer:modelBase+index*20}))},ai:{containerPointer:field.pointer+0x300,head:aiBase,records:mined.ai.map((r,index)=>({...r,pointer:aiBase+index*20,next:index+1<mined.ai.length?aiBase+(index+1)*20:0}))}};
 const enc=decodeEncounterStream(new Uint8Array(plan.project.nitro.readFile('data/prm/encfld.bin'))),groups=enc.groups.filter(g=>g.mapId===20006);need(groups.length===1&&groups[0].conditions.every(x=>x===0),'Ordinary encounter group required');field.tables={containerPointer:field.pointer+0x5c,declaredCount:groups[0].tableIds.length,rows:groups[0].tableIds.map(id=>{const t=enc.tables.find(t=>t.tableId===id);return{id,declaredCount:t.rows.length,items:t.rows.map(r=>({speciesWord:r.packedRaw,scale:convertCreatorScale(r.scaleArgument)}))};})};
 const order=mined.species.indexOf(request.species);need(order>=0,'Selected template order absent');const templates=Array.from({length:12},(_,i)=>i<mined.species.length?{slot:7+i,registryKnown:true,pointer:templateBase+i*0xb0,species:mined.species[i]}:{slot:7+i,registryKnown:true,pointer:0}),selected=templates[order],layout={modelPointer,geometryPointer,materialBlockPointer,geometryCount:template.geometryCount,dictionaryCount:template.geometryCount,entryOffset:template.entryOffset,entryStride:4,records:template.records.map(r=>({index:r.index,entryPointer:materialBlockPointer+8+template.entryOffset+r.index*4,relativeMaterialOffset:r.relativeMaterialOffset}))};
 const serial=structuredClone(session.context.serialContext);for(const s of serial.slots){const current=slots.find(r=>r.slot===s.slot);need(current,'Complete carried registry');s.rawPointer=current.pointer;s.rawHeader=current.pointer?current.headerFlags:0;s.pointer=current.pointer&&(current.headerFlags&32)?current.pointer:0;if(current.pointer)s.serial=current.nativeSerial??s.serial;}
 const protectedRanges=[{start:0x020fed44,size:4},{start:modelPointer+0x54,size:4},{start:geometryPointer,size:32},{start:materialBlockPointer,size:8+template.entryOffset+4*template.geometryCount},...serial.slots.filter(r=>r.rawPointer).map(r=>({start:r.rawPointer,size:0x198})),...serial.external.map(r=>({start:r.pointer,size:2})),{start:serial.registryAddress+8+112*4,size:48*4},...field.resources.models.entries.map(r=>({start:r.pointer,size:20})),...field.resources.ai.records.map(r=>({start:r.pointer,size:20})),{start:selected.pointer,size:0xb0},{start:component,size:44},...fields.map(f=>({start:f.pointer,size:0x314})),{start:0x020eee90,size:4},{start:0x021d7a94,size:2}];
 Object.assign(selected,{modelPointer,componentListPointer:component,actor178:65535,visualContext:{complete:true,components:[{pointer:component,tag:{...template.mode.componentTag},next:0}],layout,protectedRanges}});
 const context={creatorReached:true,globalWord:session.context.globalWord,controllerPointer:session.context.controllerPointer,managerMapId:20006,fields,inventory:structuredClone(session.context.inventory),templates,serialContext:serial,graph:session.f06Continuation.motion.graph,graphBindingVerified:true,heroXYZ:[...session.hero.xyz],terrain:session.f06Continuation.motion.terrain};const result=projectMonsterCreation(request,context,session.kernel);if(!result.resolved)return result;
 if(result.created){const slot=slots.find(s=>s.slot===result.actor.registryIndex);result.actor.e0=slot.e0Byte&0xc0;}
 return{...result,sourceAllocationKind:'logical-live-leaf-identities',sourceTemplate:{key:template.key,order,slot:7+order,configIndex:template.selectedIndex,mode:template.mode,modelMemberOffset:template.modelMemberOffset,nsbmdAlphaWordOffsets:template.records.map(r=>r.alphaOffset),cchrAlphaWordOffsets:template.records.map(r=>template.modelMemberOffset+r.alphaOffset),expandedBytes:template.expandedBytes},conditions:[...F06_CREATOR_CONDITIONS],futureActorTicksPermitted:false,visualStateResolved:false};
 }catch(error){return unknown(error.message);}
}
