import {contextRows} from './encounter-context.mjs';
import {selectFieldTables} from './at-core.mjs';
const section=document.createElement('section');section.className='field-panel';section.innerHTML=`<div class="field-heading"><h2>フィールドノード・エリア</h2><span id="field-total">NDS未読込</span></div><div class="field-controls"><label>経路 <select id="field-resource"><option value="">未選択</option></select></label><label>ゲーム内時間 <select id="field-time"><option value="">不明（候補を併合）</option><option value="0">time = 0</option><option value="2">time ≠ 0</option></select></label><button id="field-json" disabled>経路 JSON</button><button id="field-csv" disabled>全ノード CSV</button></div><div id="field-map-note" class="muted">マップを選択してください。</div><div class="field-view"><svg id="field-svg" viewBox="0 0 600 340" aria-label="ROM内モンスターノードのXZ座標"></svg><div><label>ノード <select id="field-node"><option value="">全エリア候補</option></select></label><div id="field-node-info"></div><div id="field-tables"></div></div></div><div class="muted">実座標XZのモンスター経路です。プレイヤー通行可能経路や現在位置を示すものではありません。</div>`;
document.querySelector('.workspace').append(section);
const $=id=>document.getElementById(id);let metadata=null,map=null,graph=null;
function download(name,body,type='application/json'){const url=URL.createObjectURL(new Blob([body],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
const node=(tag,attrs={})=>{const e=document.createElementNS('http://www.w3.org/2000/svg',tag);for(const[k,v]of Object.entries(attrs))e.setAttribute(k,String(v));return e;};
function emitContext(){const selected=graph?.nodes[Number($('field-node').value)],chosen=$('field-node').value!==''?selected:null;const masks=chosen?[chosen.areaMask]:graph?.areaMasks??[];const times=$('field-time').value===''?[0,2]:[Number($('field-time').value)];const context=contextRows(map?.encounterContexts??[]),tableIds=[...new Set(masks.flatMap(mask=>times.flatMap(time=>selectFieldTables(context.rows,time,mask))))];
 $('field-node-info').textContent=chosen?`ID ${chosen.id} / index ${chosen.index} / area 0x${chosen.areaMask.toString(16)} / XYZ ${chosen.position.join(', ')} / 隣接順 ${chosen.neighbors.join(', ')}`:graph?`${graph.nodeCount}ノード / ${graph.edgeCount}接続 / area ${masks.map(x=>'0x'+x.toString(16)).join(', ')}`:'静的グラフなし';
 $('field-tables').textContent=tableIds.length?`自然生成table候補: ${tableIds.join(', ')}${context.conditional.length?' / 条件付きmap参照は未解決':''}`:'対応する自然生成tableを確定できません。';
 for(const e of $('field-svg').querySelectorAll('[data-node]'))e.classList.toggle('selected',chosen?.index===Number(e.dataset.node));
 window.dispatchEvent(new CustomEvent('dq9-field-context',{detail:{mapId:map?.mapId??null,graphKey:graph?.key??null,nodeIndex:chosen?.index??null,nodeId:chosen?.id??null,areaMasks:masks,timeValues:times,rows:context.rows,tableIds,resolved:context.resolved&&masks.length>0,source:'manual-ROM-node-selection-not-live-observation'}}));
}
function draw(){const svg=$('field-svg');svg.replaceChildren();$('field-node').replaceChildren(new Option('全エリア候補',''));$('field-json').disabled=!graph;
 if(!graph?.nodes.length){emitContext();return;}const xs=graph.nodes.map(n=>n.position[0]),zs=graph.nodes.map(n=>n.position[2]),minX=Math.min(...xs),minZ=Math.min(...zs),w=Math.max(1,Math.max(...xs)-minX),h=Math.max(1,Math.max(...zs)-minZ),scale=Math.min(560/w,300/h),x=n=>20+(n.position[0]-minX)*scale,y=n=>20+(n.position[2]-minZ)*scale;
 for(const [a,b]of graph.edges){const left=graph.nodes[a],right=graph.nodes[b];svg.append(node('line',{x1:x(left),y1:y(left),x2:x(right),y2:y(right)}));}
 for(const n of graph.nodes){$('field-node').add(new Option(`ID ${n.id} · area ${n.areaMask} · ${n.position.join(', ')}`,n.index));const group=node('g',{'data-node':n.index,tabindex:0,role:'button','aria-label':`ノード ${n.id}, area ${n.areaMask}`});const c=node('circle',{cx:x(n),cy:y(n),r:5,class:'area-'+(n.areaMask%5)}),label=node('text',{x:x(n)+7,y:y(n)-6});label.textContent=String(n.id);group.append(c,label);const choose=()=>{$('field-node').value=String(n.index);emitContext();};group.onclick=choose;group.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();choose();}};svg.append(group);}emitContext();
}
function selectGraph(key,keepMap=false){graph=metadata?.fieldGraphs.graphs.find(g=>g.key===key)??null;if(!keepMap)map=null;$('field-resource').value=graph?.key??'';draw();}
window.addEventListener('dq9-rom-metadata',e=>{metadata=e.detail;map=null;graph=null;$('field-resource').replaceChildren(new Option('マップから選択',''));for(const g of metadata.fieldGraphs.graphs)$('field-resource').add(new Option(`${g.path} · ${g.nodeCount}ノード`,g.key));const s=metadata.fieldGraphs.summary;$('field-total').textContent=`${s.graphs}グラフ / ${s.nodes}ノード / ${s.edges}接続`;$('field-csv').disabled=false;draw();});
window.addEventListener('dq9-rom-release',()=>{metadata=map=graph=null;$('field-resource').replaceChildren(new Option('NDS未読込',''));$('field-total').textContent='NDS未読込';$('field-csv').disabled=true;$('field-map-note').textContent='マップを選択してください。';draw();});
window.addEventListener('dq9-map-selection',e=>{map=metadata?.records.find(r=>r.mapId===e.detail.mapId&&r.fieldCode===e.detail.fieldCode)??null;$('field-map-note').textContent=map?`表示選択: ${map.name} / ${map.mapId} / ${map.fieldGraph.status}。実機の現在位置の認識ではありません。`:'マップ未結合';selectGraph(map?.fieldGraph.key,true);});
$('field-resource').onchange=()=>{selectGraph($('field-resource').value);$('field-map-note').textContent='経路単独表示。map/areaの実機観測としては扱いません。';};$('field-node').onchange=emitContext;$('field-time').onchange=emitContext;
$('field-json').onclick=()=>{if(graph)download(graph.path+'.json',JSON.stringify({graph,mapId:map?.mapId??null,encounterContexts:map?.encounterContexts??[]},null,2));};
$('field-csv').onclick=()=>{if(!metadata)return;const q=x=>'"'+String(x??'').replaceAll('"','""')+'"';const rows=[['graph','index','id','areaMask','x','y','z','neighbors']];for(const g of metadata.fieldGraphs.graphs)for(const n of g.nodes)rows.push([g.path,n.index,n.id,n.areaMask,...n.position,n.neighbors.join(';')]);download('dq9-field-nodes.csv','\ufeff'+rows.map(r=>r.map(q).join(',')).join('\r\n'),'text/csv;charset=utf-8');};
