import{need}from'./standalone-pool-core.mjs';
import{previewLocalBackground,parseBackgroundRecipes}from'./standalone-background-input.mjs';
import{preparePipelineContext,calibratePipeline,runTrainingPipeline}from'./standalone-training-pipeline.mjs?v=integer-scale-source-20261007-1102';
import{inferRetainedFrame}from'./standalone-retained-inference.mjs';
import{DEADLINE_UTC}from'./standalone-train-core.mjs';
const $=id=>document.getElementById(id);let busy=false,controller=null,context=null,report=null,previews=null,lastProgress=0,latestDownload=null;
const show=value=>{$('status').textContent=value.phase??(value.completed?'完了':value.passed===false?'未完了 / 確認が必要':'結果');$('report').textContent=JSON.stringify(value,null,2);};
const progress=value=>{if(performance.now()-lastProgress<150)return;lastProgress=performance.now();show(value);};
function refresh(){for(const element of document.querySelectorAll('input,button,select'))element.disabled=busy;$('stop').disabled=!busy;for(const split of['train','validation'])$(split+'-confirm').disabled=busy||!previews;$('start').disabled=busy||!context?.calibration||!$('start-confirm').checked;$('save-report').disabled=busy||!report;$('save-checkpoint').disabled=busy||!context;$('predict').disabled=busy||!context?.job||context.job.status!=='complete';}
function requestDownload(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
async function run(kind,task){if(busy)return;busy=true;controller=new AbortController();refresh();try{report=await task(controller.signal);show(report);}catch(error){if(kind==='calibration'){if(context)context.calibration=null;$('start-confirm').checked=false;}report={passed:false,incomplete:error.incomplete??false,phase:kind+'-blocked',name:error.name,code:error.code??null,message:error.message,checkpointId:error.checkpointId??null,trainingState:error.trainingState??null,deadlineUTC:DEADLINE_UTC};show(report);if(kind==='calibration'&&error.name==='AbortError'){context?.dispose();context=null;}}finally{try{if(context)context.job=await context.dataStore.getJob(context.job.id);}catch(error){if(kind==='calibration'){if(context)context.calibration=null;$('start-confirm').checked=false;}report={passed:false,phase:'storage-recheck-failed',message:error.message,previousResult:report};show(report);}finally{busy=false;controller=null;refresh();}}}
function invalidate(){if(busy)return;previews=null;for(const split of['train','validation'])$(split+'-confirm').checked=false;context?.dispose();context=null;latestDownload=null;$('start-confirm').checked=false;refresh();}
for(const id of['rom','train-file','train-time','train-group','validation-file','validation-time','validation-group'])$(id).addEventListener('change',invalidate);$('epochs').addEventListener('change',()=>{if(context)context.calibration=null;$('start-confirm').checked=false;refresh();});$('start-confirm').addEventListener('change',refresh);
$('preview').onclick=()=>run('preview',async signal=>{context?.dispose();context=null;previews=null;const found=[];for(const split of['train','validation']){const file=$(split+'-file').files[0],recipes=/\.(png|jpe?g)$/i.test(file?.name??'')?[{}]:parseBackgroundRecipes($(split+'-time').value),container=$(split+'-pool');container.replaceChildren();for(let i=0;i<recipes.length;i++){const card=document.createElement('figure'),canvas=document.createElement('canvas'),caption=document.createElement('figcaption');canvas.width=320;canvas.height=240;caption.textContent=`${split} ${i+1}: ${recipes[i].timeSeconds??'image'}s ${recipes[i].crop?.join(',')??''}`;card.append(canvas,caption);container.append(card);const result=await previewLocalBackground(file,{split,group:$(split+'-group').value,...recipes[i],canvas,signal,onProgress:progress});found.push(result);}$(split+'-confirm').checked=false;}previews=found;return{phase:'background-preview-ready',negativeConfirmationRequired:true,fullProfileRequires:'At least4 distinct reviewed background frames per split',backgrounds:found.map(({descriptor,source})=>({descriptor,source})),privatePixelsUploaded:false};});
$('calibrate').onclick=()=>run('calibration',async signal=>{if(context)context.calibration=null;$('start-confirm').checked=false;need(previews,'先に各録画4枚以上の背景プールを表示してください');need($('train-confirm').checked&&$('validation-confirm').checked,'表示された全背景画像が敵なしであることを確認してください');if(!context)context=await preparePipelineContext({romFile:$('rom').files[0],backgrounds:previews.map(b=>({...b,descriptor:{...b.descriptor,negativeConfirmed:true}})),signal,onProgress:progress});const result=await calibratePipeline(context,{epochs:Number($('epochs').value),signal,onProgress:progress});return{phase:'calibration-passed',...result,fullRunStarted:false};});
function predictionInput(){const source=$('prediction-source').value;return{file:source==='custom'?$('prediction-file').files[0]:$(source+'-file').files[0],timeSeconds:Number($('prediction-time').value),canvas:$('prediction-preview')};}
$('start').onclick=()=>run('full-run',async signal=>{need(context?.calibration&&$('start-confirm').checked,'実測結果と全実行を確認してください');if($('auto-predict').checked)need(predictionInput().file,'完了後の予測ファイルがありません');const result=await runTrainingPipeline(context,{confirmed:true,signal,onProgress:progress});latestDownload=result.download;let checkpointDownloadRequested=false,downloadError=null;try{requestDownload(result.download.file,result.download.name);checkpointDownloadRequested=true;}catch(error){downloadError={name:error.name,message:error.message};}let prediction=null,predictionError=null;if($('auto-predict').checked&&Date.now()<Date.parse(DEADLINE_UTC)-20000){try{prediction=await inferRetainedFrame(context,{...predictionInput(),checkpointId:result.report.checkpointId,signal,onProgress:progress});}catch(error){predictionError={name:error.name,message:error.message};}}return{phase:'training-finished',...result.report,prediction,predictionError,checkpointDownloadRequested,downloadError,downloadDiskCompletionVerified:false};});
$('stop').onclick=()=>{controller?.abort();$('status').textContent='現在の処理後に停止し、有効な学習状態を保存します';};
$('predict').onclick=()=>run('prediction',async signal=>{need(context,'ローカル準備状態がありません');return{phase:'retained-frame-prediction',...await inferRetainedFrame(context,{...predictionInput(),signal,onProgress:progress})};});
$('save-report').onclick=()=>{if(report&&!busy)requestDownload(new Blob([JSON.stringify(report,null,2)],{type:'application/json'}),'dq9-standalone-training-report.json');};
$('save-checkpoint').onclick=()=>run('checkpoint-export',async signal=>{need(context,'ローカル準備状態がありません');if(!latestDownload){const text=localStorage.getItem('dq9-standalone-resume-v1:'+context.job.id);need(text,'検証済み学習チェックポイントがありません');const pointer=JSON.parse(text),record=await context.checkpointStore.readCheckpoint(pointer.id,{expectedBinding:pointer.binding,signal});latestDownload=await context.checkpointStore.exportCheckpoint(record,{expectedBinding:pointer.binding,signal});}requestDownload(latestDownload.file,latestDownload.name);return{phase:'checkpoint-download-requested',id:latestDownload.id,bytes:latestDownload.bytes,downloadDiskCompletionVerified:false};});
$('storage').onclick=()=>run('storage',async()=>{need(context,'実測を開始すると専用保存領域が表示されます');return{phase:'storage',data:await context.dataStore.status(),checkpoints:await context.checkpointStore.status()};});
setInterval(()=>{const ms=Date.parse(DEADLINE_UTC)-Date.now();$('clock').textContent=ms>0?`21:30 JSTまで約${Math.ceil(ms/60000)}分。時間見込みは開始時にも再確認します`:'予定期限を過ぎています。追加学習は開始しません';},1000);refresh();
