import{loadDetectorAssets}from'./tiny-yolo-assets.mjs';
import{decodeModel,encodeModel}from'./tiny-yolo-model.mjs';
import{createDataStore}from'./standalone-pool-store.mjs';
import{openCheckpointStore}from'./standalone-checkpoint-store.mjs';
import{createTrainingSession,makeBinding}from'./standalone-train-run.mjs';
import{epochOrder,VALIDATION_SPEC,createMetrics,addImageMetrics,finalizeMetrics}from'./standalone-train-core.mjs';
import{decodeDetections}from'./tiny-yolo-decode.mjs';
import{assertShape,assertFiniteValues}from'./tiny-yolo-validation.mjs';
import{need,abort,sha256,hashValue}from'./standalone-pool-core.mjs';
import{AB_VERSION,EXPECTED_PARENT_ID,compareABMetrics,requireABBudget}from'./standalone-loss-ab-core.mjs';
import{selectThreeTargetData,subsetStore,orderedSubsetImages}from'./standalone-three-target.mjs';
export{AB_VERSION};
async function verifiedLoss(name,expectedSHA,signal){
 need(/^[a-f0-9]{64}$/.test(expectedSHA),'Pinned loss SHA required');const response=await fetch(new URL(name,import.meta.url),{cache:'no-cache',signal});need(response.ok,'Loss source unavailable');const bytes=await response.arrayBuffer();need(bytes.byteLength>0&&bytes.byteLength<128*1024,'Invalid loss source size');const hash=await sha256(bytes);need(hash===expectedSHA,'Loss source differs from pinned experiment');const url=URL.createObjectURL(new Blob([bytes],{type:'text/javascript'}));try{return{module:await import(url),sha256:hash};}finally{URL.revokeObjectURL(url);}
}
export async function listCompletedDetectorData(){const store=await createDataStore();try{const results=[];for(const row of(await store.status()).jobs.filter(x=>x.status==='complete')){const parent=await store.getJob(row.id),subset=await selectThreeTargetData(parent);results.push({...row,subsetPreflight:{id:subset.id,counts:subset.manifest.counts,targets:subset.manifest.targets,negativeSourceImages:subset.manifest.negativeSourceImages.length,negativeSourceGroups:subset.manifest.negativeSourceGroups,sourcePlanHashVerified:true,order512SHA256:await hashValue(orderedSubsetImages(subset.manifest.trainingIndices,512))}});}return results;}finally{store.close();}}
async function evaluate(tf,model,job,store,{signal,onProgress=()=>{},split='validation'}={}){
 const indices=job.plan.recipes.filter(r=>r.split===split).map(r=>r.index),metrics=createMetrics(),localization=createMetrics(),began=performance.now(),shape=[1,10,10,1305],per=130500,negativeByBackground=new Map(),frames=[];let completed=0;
 for(let at=0;at<indices.length;at+=2){abort(signal);const samples=await Promise.all(indices.slice(at,at+2).map(i=>store.readImage(job.id,i))),data=new Float32Array(samples.length*320*320*3);samples.forEach((s,i)=>data.set(s.rgb,i*320*320*3));const pixels=tf.tensor4d(data,[samples.length,320,320,3]);let raw;try{raw=model.forward(pixels);assertShape(raw.shape,[samples.length,10,10,1305],'A/B validation');const values=await raw.data();assertFiniteValues(values,samples.length*per,'A/B validation');for(let i=0;i<samples.length;i++){const predictions=decodeDetections(values.subarray(i*per,(i+1)*per),shape,{classMap:job.plan.target.classMap,inputSize:320,sourceWidth:320,sourceHeight:240,...VALIDATION_SPEC}),truth=samples[i].frame;frames.push({sourceIndex:samples[i].index??truth.index,inputPixelSHA256:samples[i].pixelSHA256??null,truth,predictions});addImageMetrics(metrics,truth,predictions);addImageMetrics(localization,{...truth,boxes:truth.boxes.map(b=>({...b,label:0}))},predictions.map(p=>({...p,label:0})));if(!truth.boxes.length){const key=truth.recipe.backgroundSHA256,entry=negativeByBackground.get(key)??{images:0,imagesWithPredictions:0,predictions:0};entry.images++;entry.imagesWithPredictions+=Number(predictions.length>0);entry.predictions+=predictions.length;negativeByBackground.set(key,entry);}}completed+=samples.length;}finally{raw?.dispose();pixels.dispose();}if(completed%32===0||completed===indices.length){onProgress({phase:split==='train'?'training-fit-evaluation':'validation',completed,total:indices.length});await new Promise(resolve=>setTimeout(resolve,0));}}
 return{split,images:completed,frames,elapsedMs:performance.now()-began,species:finalizeMetrics(metrics),classAgnosticAtSameScoreGate:finalizeMetrics(localization),negativeBackgrounds:Object.fromEntries(negativeByBackground),thresholds:VALIDATION_SPEC,scope:split==='train'?'Training-fit resubstitution on216 selected images. Not unseen accuracy.':'Reused synthetic/development split. Class-agnostic metric ignores labels only, not the fixed score/NMS gates.'};
}

async function predictRealFrames(tf,model,job,frames,{signal,onProgress,variant}){
 const results=[];for(let i=0;i<frames.length;i++){abort(signal);const f=frames[i],data=new Float32Array(320*320*3);data.set(f.pixels.rgb);const pixels=tf.tensor4d(data,[1,320,320,3]);let raw;try{raw=model.forward(pixels);assertShape(raw.shape,[1,10,10,1305],'A/B real prediction');const values=await raw.data();assertFiniteValues(values,130500,'A/B real prediction');const result={frameIndex:i,source:f.source,decodedPixelSHA256:f.descriptor.pixelSHA256,predictions:decodeDetections(values,raw.shape,{classMap:job.plan.target.classMap,inputSize:320,sourceWidth:320,sourceHeight:240,...VALIDATION_SPEC}),scope:'Development-exposed local-frame predictions. No automatic accuracy assertion.'};results.push(result);onProgress({phase:'real-prediction',variant,...result});}finally{raw?.dispose();pixels.dispose();}}
 return results;
}
export async function exportABCheckpoint(branch,{signal}={}){
 need(branch?.checkpointId&&branch.binding,'Verified candidate checkpoint required');const store=await openCheckpointStore({maxBytes:8*1024**3,maxRecords:64});try{const record=await store.readCheckpoint(branch.checkpointId,{expectedBinding:branch.binding,signal});need(record.manifest.provenance.parentCheckpointId===EXPECTED_PARENT_ID,'Candidate parent changed');return await store.exportCheckpoint(record,{expectedBinding:branch.binding,signal});}finally{store.close();}
}

export async function runLossAB({datasetId,steps=512,signal,onProgress=()=>{},saveCandidates=true,realFrames=[]}={}){
 need(Array.isArray(realFrames)&&realFrames.length<=8&&realFrames.every(f=>f?.pixels?.rgb instanceof Uint8Array&&f.pixels.rgb.length===320*240*3),'At most8 locally decoded real frames are allowed');need(Date.now()+10*60*1000<=Date.parse('2026-10-01T12:30:00.000Z')-120000,'Reserve ten minutes before the21:30JST save cutoff');
 need(typeof document==='undefined'||document.visibilityState==='visible','Use a foreground tab for this newly authorized bounded experiment');need(Number.isInteger(steps)&&steps>=1&&steps<=512,'A/B is limited to1..512 steps per branch');const started=performance.now(),progress=onProgress,check=()=>{abort(signal);need(Date.now()<Date.parse('2026-10-01T12:30:00.000Z')-120000,'The21:30JST save reserve has been reached');need(performance.now()-started<10*60*1000,'The ten-minute experiment budget has been reached');};onProgress=value=>{check();progress({...value,visibility:typeof document==='undefined'?'unavailable':document.visibilityState});};check();let dataStore,checkpointStore,model,optimizer,session,report;
 try{
  dataStore=await createDataStore();checkpointStore=await openCheckpointStore({maxBytes:8*1024**3,maxRecords:64,onProgress:e=>onProgress({phase:'checkpoint',event:e})});
  const parentJob=await dataStore.getJob(datasetId),job=parentJob;need(job?.status==='complete'&&job.nextIndex===job.totalSamples,'Select a complete saved pooled dataset');const pointerText=localStorage.getItem('dq9-standalone-resume-v1:'+datasetId);need(pointerText,'Verified parent checkpoint pointer missing');const pointer=JSON.parse(pointerText);need(pointer.id===EXPECTED_PARENT_ID,'This experiment requires the reviewed baseline checkpoint; pointer was not changed');const subset=await selectThreeTargetData(parentJob),selectedJob=subset.job,selectedStore=subsetStore(dataStore,parentJob.id,subset);const assets=await loadDetectorAssets({model:false,signal,onProgress}),tf=assets.tf,v1=await verifiedLoss('./tiny-yolo-loss.mjs',pointer.binding?.lossSHA256,signal),v2=await verifiedLoss('./tiny-yolo-loss-v3.mjs','4473afaf2a714c4531ee0430a4ad6067683c4515cf7f8f143a3813f254f46fe0',signal),lossV1=v1.module,lossV2=v2.module,v1SHA=v1.sha256,v2SHA=v2.sha256,originalBinding=await makeBinding({job,tf,assetConfig:assets.config,inputSize:320,batchSize:2,lossSourceSHA256:v1SHA});need(pointer.bindingSHA256===await hashValue(originalBinding),'Parent execution/data binding changed');const parent=await checkpointStore.readCheckpoint(pointer.id,{expectedBinding:originalBinding,signal}),parentDataSHA256=await sha256(parent.data),indices=subset.manifest.trainingIndices,order=orderedSubsetImages(indices,steps),orderSHA256=await hashValue(order),experimentId=await hashValue({version:AB_VERSION,parentCheckpointId:parent.id,orderSHA256,steps,learningRate:.00001,optimizerReset:true,v1SHA,v2SHA});
  const storage=await checkpointStore.status(),budget=requireABBudget(storage,{saveCandidates});report={version:AB_VERSION,experimentId,parentCheckpointId:parent.id,parentStep:parent.manifest.step,parentDataSHA256,datasetId,subset:subset.manifest,subsetId:subset.id,stepsPerBranch:steps,batchSize:2,learningRate:.00001,optimizerReset:true,orderSHA256,trainingClassCoverage:new Set(order.map(i=>parentJob.plan.recipes[i].label).filter(Number.isInteger)).size,thresholds:VALIDATION_SPEC,baseline:null,branches:[],fullRunAdmitted:false,newExperimentNotResume:true,backgroundExecution:'Continues when hidden; ten-minute wall budget and21:30JST save reserve still enforced. Timing estimates were measured foreground.',budget,realFrames:realFrames.map(f=>({source:f.source,decodedPixelSHA256:f.descriptor.pixelSHA256}))};
  for(const [index,variant]of[{name:'v1-control',loss:lossV1,lossSHA256:v1SHA},{name:'v3-bce-per-image',loss:lossV2,lossSHA256:v2SHA}].entries()){
   abort(signal);onProgress({phase:'branch-load',variant:variant.name,parentCheckpointId:parent.id});const decoded=decodeModel(tf,parent.data,parent.manifest);for(const{tensor}of decoded.optimizer)tensor.dispose();model=decoded.detector;optimizer=tf.train.adam(.00001);if(index===0){report.baseline=await evaluate(tf,model,selectedJob,selectedStore,{signal,onProgress:p=>onProgress({...p,variant:'unmodified-parent'})});report.baseline.trainingFit=await evaluate(tf,model,selectedJob,selectedStore,{signal,split:'train',onProgress:p=>onProgress({...p,variant:'unmodified-parent'})});report.baseline.realPredictions=await predictRealFrames(tf,model,job,realFrames,{signal,onProgress,variant:'unmodified-parent'});}
   // New optimizer for both arms. Only objective normalization and the objectness loss differ.
   const forward=model.forward.bind(model),wrapped={...model,step(pixels,targets,opt){return opt.minimize(()=>tf.tidy(()=>variant.loss.detectorLoss(tf,forward(pixels),targets).totalLoss),true,model.variables);}},binding=structuredClone(originalBinding);binding.model.sourceSHA256=parentDataSHA256;binding.dataset={...binding.dataset,planSHA256:subset.id,contentChainSHA256:selectedJob.chain,totalSamples:selectedJob.totalSamples,completedSamples:selectedJob.nextIndex,trainingSamples:indices.length};binding.lossSHA256=variant.lossSHA256;session=createTrainingSession({tf,model:wrapped,optimizer,job:selectedJob,dataStore:selectedStore,checkpointStore,binding,calibration:true,onProgress:p=>onProgress({...p,variant:variant.name})});const training=[];while(session.state.globalStep<steps){abort(signal);const chunk=await session.trainChunk({maxSteps:Math.min(64,steps-session.state.globalStep),signal});training.push(chunk);if(chunk.epochComplete&&session.state.globalStep<steps)session.advanceEpoch();}const validation=await evaluate(tf,model,selectedJob,selectedStore,{signal,onProgress:p=>onProgress({...p,variant:variant.name})}),branch={variant:variant.name,lossVersion:variant.loss.LOSS_VERSION,lossSHA256:variant.lossSHA256,trainingState:session.state,training,validation,checkpointId:null,binding};branch.trainingFit=await evaluate(tf,model,selectedJob,selectedStore,{signal,split:'train',onProgress:p=>onProgress({...p,variant:variant.name})});branch.realPredictions=await predictRealFrames(tf,model,job,realFrames,{signal,onProgress,variant:variant.name});
   report.branches.push(branch);if(saveCandidates){const encoded=await encodeModel(tf,model,{optimizer,step:session.state.globalStep,provenance:{experimentId,parentCheckpointId:parent.id,parentStep:parent.manifest.step,optimizerReset:true,orderSHA256,subset:subset.manifest,lossVersion:variant.loss.LOSS_VERSION,lossSHA256:variant.lossSHA256,classMap:job.plan.target.classMap,scope:'Bounded matched three-target A/B diagnostic only; not deployment-ready or an identical resume',validation:{images:validation.images,species:validation.species,classAgnosticAtSameScoreGate:validation.classAgnosticAtSameScoreGate,negativeBackgrounds:validation.negativeBackgrounds,thresholds:validation.thresholds},trainingFit:{images:branch.trainingFit.images,species:branch.trainingFit.species,classAgnosticAtSameScoreGate:branch.trainingFit.classAgnosticAtSameScoreGate}}}),saved=await checkpointStore.saveCheckpoint(encoded,{binding,trainingState:session.state,signal});branch.checkpointId=saved.id;branch.checkpointTimings=saved.timings;}
   onProgress({phase:'branch-complete',variant:variant.name,summary:{species:validation.species.totals,precision:validation.species.precision,recall:validation.species.recall,negativeFPR:validation.species.negativeImageFalsePositiveRate,classAgnosticRecall:validation.classAgnosticAtSameScoreGate.recall},checkpointId:branch.checkpointId});session.dispose();session=null;model=null;optimizer=null;
  }
  need(await sha256(parent.data)===parentDataSHA256,'Parent bytes changed unexpectedly');const verifiedParent=await checkpointStore.readCheckpoint(parent.id,{expectedBinding:originalBinding,signal});need(verifiedParent.id===parent.id,'Parent checkpoint no longer verifies');report.baselinePreserved=true;report.elapsedMs=performance.now()-started;report.comparison=compareABMetrics(...report.branches.map(x=>x.validation.species));return report;
 }catch(error){if(error.committed&&error.checkpointId&&report){report.unverifiedCommittedCheckpoint={id:error.checkpointId,verificationComplete:false,message:error.message};}error.partialReport=report??null;throw error;}finally{if(session)session.dispose();else{model?.dispose();optimizer?.dispose();}dataStore?.close();checkpointStore?.close();}
}
