import {CameraInput} from './camera-input.mjs';
import {buildMapNameDictionary,MapNameMatcher} from './map-name-match.mjs';
const section=document.createElement('section');section.className='video-panel';section.innerHTML=`<div class="video-heading"><h2>映像入力・マップ名候補</h2><span id="video-status">未接続</span></div><div class="video-controls"><select id="camera-list" aria-label="カメラ"></select><button id="camera-refresh">一覧更新</button><button id="camera-connect">接続</button><button id="camera-stop">停止</button><button id="runtime-fonts" disabled>NDSフォント生成</button><button id="video-log">観測ログ JSON</button><label><input id="position-enabled" type="checkbox">マップ位置照合</label></div><details><summary>映像範囲・照合設定</summary><p>映像上をドラッグして上画面を指定し、上画面プレビュー上をドラッグしてマップ名の文字部分を指定します。</p><div class="video-controls"><label>白閾値 <input id="video-threshold" type="number" min="0" max="255" value="220"></label><label>読取間隔 ms <input id="video-interval" type="number" min="250" max="10000" value="500"></label><button id="video-roi-reset">範囲リセット</button></div><label>縮尺候補 <input id="position-scales" value="0.5" size="12" aria-label="128px映像に対するROM画像縮尺"></label><span id="video-roi"></span></details><div class="video-grid"><div class="video-source"><video id="camera-video" autoplay muted playsinline></video><canvas id="camera-roi-overlay"></canvas></div><div><canvas id="upper-preview" width="256" height="192"></canvas><canvas id="name-preview" width="128" height="24"></canvas><div id="position-status" class="muted">マップ照合未開始。表示中のROMマップを参照します。</div><div id="font-status" class="muted">フォントは投入NDSからメモリ内生成します。</div></div><div id="name-candidates">認識候補はまだありません。</div></div><div class="muted">候補スコアは実映像で未校正です。表示マップ選択、実機位置、証明済みAT下限を混同しません。</div>`;
document.querySelector('.workspace').append(section);
const $=id=>document.getElementById(id),video=$('camera-video'),upper=$('upper-preview'),nameCanvas=$('name-preview'),overlay=$('camera-roi-overlay');
const frame=document.createElement('canvas');frame.width=256;frame.height=192;const frameCtx=frame.getContext('2d',{willReadFrequently:true}),upperCtx=upper.getContext('2d'),nameCtx=nameCanvas.getContext('2d',{willReadFrequently:true});
let records=[],matcher=null,busy=false,generation=0,romEpoch=0,faces=[],observations=[],lastSignature='',drag=null;
let roi={screen:{x:0,y:0,w:1,h:1},name:{x:.35,y:0,w:.65,h:.22}};
try{const saved=JSON.parse(localStorage.getItem('dq9-at-video-roi')||'null');if(saved)for(const key of ['screen','name']){const r=saved[key];if(r&&[r.x,r.y,r.w,r.h].every(Number.isFinite)&&r.x>=0&&r.y>=0&&r.w>0&&r.h>0&&r.x+r.w<=1.001&&r.y+r.h<=1.001)roi[key]=r;}}catch{}

const positionWorker=new Worker(new URL('./position-worker.mjs',import.meta.url),{type:'module'}),small=document.createElement('canvas');small.width=128;small.height=96;const smallCtx=small.getContext('2d',{willReadFrequently:true});
let positionEpoch=0,positionPending=false,positionReady=false,frameSerial=0,lastPosition=null,lastPositionSignature='';
window.addEventListener('dq9-map-image',e=>{positionEpoch++;positionPending=false;positionReady=false;lastPosition=null;lastPositionSignature='';positionWorker.postMessage({type:'reference',epoch:positionEpoch,image:e.detail});$('position-status').textContent=e.detail?'ROM参照マップを準備中':'ROMマップ未選択';});
positionWorker.onmessage=({data:m})=>{if(m.epoch!==positionEpoch)return;if(m.type==='reference'){positionReady=m.ok;return;}positionPending=false;if(!m.ok){$('position-status').textContent=m.error;return;}lastPosition=m.result;const b=lastPosition.best;$('position-status').textContent=b?`画像位置 ${lastPosition.resolved?'候補一致':'未確定'} · x ${b.dx}, y ${b.dy}, scale ${b.scale} · 類似度 ${b.score.toFixed(3)} / 差 ${lastPosition.margin.toFixed(3)} · 実座標は未確定`:'位置候補なし';const signature=JSON.stringify([lastPosition.mapId,lastPosition.resolved,b?.dx,b?.dy,b?.scale]);if(signature!==lastPositionSignature){lastPositionSignature=signature;remember({...lastPosition,capturedAt:m.capturedAt,videoTime:m.videoTime,minimumProvenATCalls:0});}};
positionWorker.onerror=e=>{positionPending=false;positionReady=false;$('position-status').textContent=e.message;};
function positionFrame(){if(!$('position-enabled').checked||positionPending||!positionReady)return;smallCtx.imageSmoothingEnabled=true;smallCtx.drawImage(frame,0,0,128,96);const data=smallCtx.getImageData(0,0,128,96),n=roi.name,scales=$('position-scales').value.split(/[ ,]+/).map(Number).filter(x=>x>0&&x<=4).slice(0,6);positionPending=true;positionWorker.postMessage({type:'frame',epoch:positionEpoch,frameSerial:++frameSerial,capturedAt:new Date().toISOString(),videoTime:video.currentTime,frame:{width:128,height:96,rgba:data.data},options:{scales:scales.length?scales:[.5],excluded:[{x:n.x*128,y:n.y*96,w:n.w*128,h:n.h*96}]}},[data.data.buffer]);}

function status(text){$('video-status').textContent=text;}
function config(){try{localStorage.setItem('dq9-at-video-roi',JSON.stringify(roi));}catch{}$('video-roi').textContent=`上画面 ${JSON.stringify(roi.screen)} / 文字 ${JSON.stringify(roi.name)}`;drawBoxes();}
function drawBoxes(){const w=video.videoWidth||640,h=video.videoHeight||480;if(overlay.width!==w||overlay.height!==h){overlay.width=w;overlay.height=h;}const ctx=overlay.getContext('2d');ctx.clearRect(0,0,w,h);ctx.strokeStyle='#ce3b2e';ctx.lineWidth=Math.max(2,w/400);ctx.strokeRect(roi.screen.x*w,roi.screen.y*h,roi.screen.w*w,roi.screen.h*h);}
function point(e,element){const r=element.getBoundingClientRect();return {x:Math.min(1,Math.max(0,(e.clientX-r.left)/r.width)),y:Math.min(1,Math.max(0,(e.clientY-r.top)/r.height))};}
for(const[element,key]of [[overlay,'screen'],[upper,'name']]){element.onpointerdown=e=>{element.setPointerCapture(e.pointerId);drag={key,start:point(e,element),element};};element.onpointerup=e=>{if(!drag||drag.element!==element)return;const end=point(e,element),start=drag.start;drag=null;const r={x:Math.min(start.x,end.x),y:Math.min(start.y,end.y),w:Math.abs(end.x-start.x),h:Math.abs(end.y-start.y)};if(r.w>.01&&r.h>.01){roi[key]=r;generation++;config();}};}
async function cameras(){const selected=$('camera-list').value,devices=await camera.list();$('camera-list').replaceChildren(new Option('既定のカメラ',''));devices.forEach((d,i)=>$('camera-list').add(new Option(d.label||`Camera ${i+1}`,d.deviceId)));$('camera-list').value=devices.some(d=>d.deviceId===selected)?selected:(devices.find(d=>/obs virtual camera/i.test(d.label))?.deviceId||'');}
function remember(o){observations.push(o);if(observations.length>1000)observations.shift();window.dispatchEvent(new CustomEvent('dq9-video-observation',{detail:o}));}
async function readFrame(timestamp){if(busy)return;busy=true;const serial=generation,current=matcher;try{const r=roi.screen;frameCtx.imageSmoothingEnabled=false;frameCtx.drawImage(video,r.x*video.videoWidth,r.y*video.videoHeight,r.w*video.videoWidth,r.h*video.videoHeight,0,0,256,192);upperCtx.drawImage(frame,0,0);drawBoxes();const n=roi.name,x=Math.floor(n.x*256),y=Math.floor(n.y*192),w=Math.min(256-x,Math.max(1,Math.floor(n.w*256))),h=Math.min(192-y,Math.max(1,Math.floor(n.h*192)));nameCanvas.width=w;nameCanvas.height=h;nameCtx.drawImage(frame,x,y,w,h,0,0,w,h);upperCtx.strokeStyle='#ce3b2e';upperCtx.strokeRect(x,y,w,h);positionFrame();if(lastPosition?.resolved&&lastPosition.best){const p=lastPosition.best;upperCtx.save();upperCtx.strokeStyle='#327c59';upperCtx.lineWidth=1;upperCtx.strokeRect(p.dx*2,p.dy*2,lastPosition.imageWidth*p.scale*2,lastPosition.imageHeight*p.scale*2);upperCtx.restore();}if(!current){status('映像入力中 · NDSフォント未生成');return;}
 const result=await current.match(nameCtx.getImageData(0,0,w,h),{threshold:Math.max(0,Math.min(255,Number($('video-threshold').value)||0))});if(serial!==generation||current!==matcher)return;
 const observation={kind:'video-map-name-candidates',capturedAt:new Date().toISOString(),videoTime:video.currentTime,frameTimestamp:timestamp,...result,roi:structuredClone(roi),positionResolved:false,areaResolved:false,minimumProvenATCalls:0};
 $('name-candidates').replaceChildren();for(const c of result.candidates){const button=document.createElement('button');button.className='name-candidate';button.textContent=`${c.name} · diff ${c.difference} · ${c.size} · map ${c.mapIds.join(', ')}`;button.onclick=()=>{if(c.mapIds.length===1)window.dispatchEvent(new CustomEvent('dq9-view-map-request',{detail:{mapId:c.mapIds[0],source:'human-selection-from-video-candidates'}}));else status('同名mapが複数あります。一覧から選択してください。');};$('name-candidates').append(button);}if(!result.candidates.length)$('name-candidates').textContent='文字候補なし。範囲と白閾値を確認してください。';
 const signature=result.candidates.map(c=>c.name).join('|');if(signature!==lastSignature){lastSignature=signature;remember(observation);}status(`映像入力中 · ${result.evaluated??0}候補評価 · AT下限へ自動加算なし`);
 }finally{busy=false;if(current&&current!==matcher)current.destroy();}}
const camera=new CameraInput(video,readFrame,error=>status(error.message));
$('camera-refresh').onclick=()=>cameras().catch(e=>status(e.message));$('camera-connect').onclick=async()=>{try{await camera.connect($('camera-list').value);await cameras();status('映像接続');}catch(e){status(e.message);}};$('camera-stop').onclick=()=>{generation++;camera.stop();remember({kind:'video-gap',capturedAt:new Date().toISOString(),minimumProvenATCalls:0});status('映像停止 · 証明済みAT下限は維持');};
$('video-interval').onchange=()=>camera.interval=Math.max(250,Math.min(10000,Number($('video-interval').value)||500));$('video-roi-reset').onclick=()=>{roi={screen:{x:0,y:0,w:1,h:1},name:{x:.35,y:0,w:.65,h:.22}};generation++;config();};
$('runtime-fonts').onclick=()=>{$('runtime-fonts').disabled=true;$('font-status').textContent='投入NDSから生成中';window.dispatchEvent(new CustomEvent('dq9-font-request'));};
window.addEventListener('dq9-rom-metadata',e=>{records=e.detail.records;$('runtime-fonts').disabled=false;});
window.addEventListener('dq9-font-error',e=>{$('font-status').textContent=e.detail;$('runtime-fonts').disabled=!records.length;});
window.addEventListener('dq9-runtime-fonts',async e=>{const serial=romEpoch,result=e.detail;try{const dictionary=buildMapNameDictionary(result.glyphsBySize,records),next=new MapNameMatcher(dictionary),old=matcher;matcher=next;if(old&&!busy)old.destroy();for(const face of faces)document.fonts.delete(face);faces=[];for(const f of result.fonts){const size=f.name.match(/font_(.+)\.ttf/)?.[1]||'runtime',face=new FontFace('DQ9ROM'+size,f.data);await face.load();if(serial!==romEpoch)return;document.fonts.add(face);faces.push(face);}if(serial!==romEpoch)return;$('font-status').textContent=`${result.summary.fontFiles}フォント / ${Object.entries(result.summary.glyphs).map(([size,n])=>`${size}: ${n}`).join(' / ')} / マップ名 ${dictionary.templates.length}候補`;status('ROMフォント準備完了');}catch(error){$('font-status').textContent=error.message;}finally{$('runtime-fonts').disabled=!records.length;}});
window.addEventListener('dq9-rom-release',()=>{generation++;romEpoch++;records=[];const old=matcher;matcher=null;if(old&&!busy)old.destroy();for(const face of faces)document.fonts.delete(face);faces=[];$('runtime-fonts').disabled=true;$('font-status').textContent='NDS未投入';$('name-candidates').textContent='NDS解放済み';lastSignature='';});
$('video-log').onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify({format:'dq9-video-observations',version:1,observations,truncatedToLast:1000,confidenceCalibrated:false},null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='dq9-video-observations.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};window.addEventListener('pagehide',()=>{camera.stop();matcher?.destroy();positionWorker.terminate();});config();cameras().catch(e=>status(e.message));
